### ISSUE TITLE
Cannot start docusaurus

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1018]
I heard feedback from some developers that were unable to contribute to the docs. Here is their screenshot:

![image](https://user-images.githubusercontent.com/1042667/156070025-3763444a-4fbd-4928-a417-70714e0d02d5.png)

I pulled `master` and was able to reproduce this problem.

**Comment by thisisjoshford** [comment]
Works fine locally for me but was able to reproduce in a VM... Working on a fix now.

**Comment by gagdiez** [comment]
@thisisjoshford Having exactly the same problem, I am working on solving it. If you have any ideas please let me know

**Comment by gagdiez** [comment]
Managed to make it compile, but the search bar is not working locally
