### ISSUE TITLE
[DOC] start_node script doesn't work out of the box without docker

### ISSUE THREAD

**Issue by mfornet** [near/docs#102]
We should add to the documentation (or to the `start_node` script) comment by @ailisp from
https://github.com/nearprotocol/nearcore/pull/1551.

**Comment by amgando** [comment]
these are all the `start_*` scripts we have in `nearcore`

```
./scripts/start_localnet.py
./scripts/start_staging_testnet.py
./scripts/start_stakewars.py
./scripts/start_testnet.py
./scripts/start_unittest.py

./pytest/tests/adversarial/start_from_genesis.py
./pytest/tests/sanity/restart.py
```

**Comment by amgando** [comment]
closing since this is replaced by `nearup`
