### ISSUE TITLE
[DOC] Document on-chain storage constraints

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1058]
Document on-chain storage constraints. 

If, for example, someone wants to put an NFT purely on-chain (rather than IPFS or some other decentralized storage solution) let's outline constraints.

- almost unlimited amount of storage but will have to pay 1 $NEAR per 100kb
- users will be limited to 4MB per contract call upload due to MAX_GAS constraints

**Comment by doriancrutcher** [comment]
https://github.com/near/docs/pull/1335

PR created for this issue. Reviewed by @gagdiez  and @bucanero. 

If additional information is needed would be happy to add to this PR. 

But for now want to close this issue
