### ISSUE TITLE
[DOC] Spanish translation of docs

### ISSUE THREAD

**Issue by waldmatias** [near/docs#1104]
**Is your feature request related to a problem? Please describe.**
Currently there is no spanish version of NEAR docs :) 

**Describe the solution you'd like**
All documentation translated to spanish would be nice, but at the very least we should start with the Concepts. 
https://docs.near.org/docs/concepts/

**Additional context**
I've already contributed to the NEAR Lake docs (PRs) as well as provided Spanish-English translations for content from NEAR University (under a fellowship). Would be more than happy to work on v.1 for spanish translation for NEAR docs!

**Comment by waldmatias** [comment]
Spanish (es) translation will be possible if enabled in Docusaurus: 
https://github.com/near/docs/blob/master/website/docusaurus.config.js
Line #170

**Comment by bucanero** [comment]
The translation project for Docs is managed on Crowdin. You can find information here: https://wiki.near.org/contribute/localization
