### ISSUE TITLE
[BUG] Broken links to AS and JS sdks in docs

### ISSUE THREAD

**Issue by MaxGraey** [near/docs#1111]
**Describe the bug** 🐞
404 pages

**Expected behavior**
Links to documentation

**Location** 🎯
on https://near.org/developer-tools this links are broken (404):

- [near-sdk-as / Read the Docs  >](https://docs.near.org/develop/contracts/as/intro)
- [near-api-js / Read the Docs  >](https://docs.near.org/api/javascript-library)
- [near-sandbox / Read the Docs  >](https://docs.near.org/develop/contracts/sandbox)

**Comment by bucanero** [comment]
Redirects have been added. Thanks for reporting these broken links. 👍
