### ISSUE TITLE
[DOC] Update "Local Development on Local Node"

### ISSUE THREAD

**Issue by potatodepaulo** [near/docs#114]
**Is your feature request related to a problem? Please describe.**
The problem is that this document is out of date: https://docs.nearprotocol.com/docs/local-setup/local-dev-node 

**Describe the solution you'd like**
This page should be titled "Local Development on Local Network" and needs a small re-write.

It should show peeps how to spin up a "local network", not a "local node". The difference in practice is simple as running "start_localnet" with an "acccounts.csv" inside of the ~/.near folder. The technical difference is that the "start_testnet" syncs with our public testnet and the former creates an entirely separate network. The separate network is more stable since it doesn't sync our breaking changes

**Additional context**
Important Definitions
* Public Testnet - The network that we maintain and run nodes for of the most up to date master branch of nearcore
* Local Testnet - The same thing as running a "Local Node"
* Local Node - Running the nearcore code on your system in a way that it syncs to the Public Testnet
* Local Network - Any branch pulled from nearcore (including staging, commit hash, or a feature branch) that starts without synching to the "Public Testnet." Two benefits are: 1) More stability because you can freeze a version 2) You can define genesis yourself for all sorts of shenanigans

![Screen Shot 2019-11-11 at 1 44 31 PM](https://user-images.githubusercontent.com/6679554/68623658-dc396100-0489-11ea-9bc3-fe4e2c346887.png)

**Comment by mattlockyer** [comment]
This appears to have been addressed:
![image](https://user-images.githubusercontent.com/321340/82498289-94347000-9aa4-11ea-8d20-0164b6669c89.png)
Re-open and tag me if you still think it's insufficient.
