### ISSUE TITLE
[DOC] 

### ISSUE THREAD

**Issue by austinabell** [near/docs#1140]
Documentation around storage costs using AssemblyScript can be misleading. 

The question was around:

https://github.com/near/docs/blob/master/docs/1.concepts/storage/storage-staking.md#example-cost-breakdown-example-cost-breakdown

Where someone using the Rust SDK was confused about the `::` extra bytes (there is no need for this) and wondering where the additional storage cost was coming from.

The docs should mention that extra bytes from the `num_extra_bytes_record` parameter (currently 40) https://github.com/near/nearcore/blob/4008f1dfd76ac2ed4c5727307e963f023e7ca8df/runtime/near-vm-logic/src/logic.rs#L2383

If the docs switch to Rust, the key should be mentioned as follows:
`- key: `b"t2o" + 0` or `[74, 32, 30, 00]` in bytes`

Rather than
`key: t2o::0`

**Is your feature request related to a problem? Please describe.**
Misleading to developers when trying to understand costs and serialization format

**Describe the solution you'd like**
Improve information for relevant SDKs. Rust and JS SDK do slightly different than these (Rust borsh serializes key after prefix, JS JSON serializes key)

**Additional context**

**Comment by thisisjoshford** [comment]
test

**Comment by thisisjoshford** [comment]
Closing this issue as storage staking docs were recently updated and we will be deprecating AS from docs.
