### ISSUE TITLE
Add details on stateless methods

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1156]
As per some discussions during a previous pull request, it was pointed out that we can add more information about stateless methods.
https://github.com/near/sdk-docs/pull/37#discussion_r692370315
This might go in the `near_bindgen` section of the docs.

**Comment by doriancrutcher** [comment]
Discussed it with the team and because this hasn't really come up in the community or internally as an issue I think I'll close this issue.

**Comment by mikedotexe** [comment]
> Discussed it with the team and because this hasn't really come up in the community or internally as an issue I think I'll close this issue.

luv u dude! hope to see you at a conference soon!
