### ISSUE TITLE
suggesting status message as a template is not a very good idea

### ISSUE THREAD

**Issue by adsick** [near/docs#1158]
so the thing is [this section](https://www.near-sdk.io/#create-a-new-project) says that 'If you only wish to develop and deploy a Rust contract, the [status message example](https://github.com/near-examples/rust-status-message) is great to use as a template or through cargo-generate.'

but status message also includes a lot of frontend which the developer might not want (esp if they use cargo generate but not npx)

another issue is that when they would like to name their smart contract they would need to modify Cargo.toml and package.json files in order to rename the contract from status message to something else (what is the point of 'generate' then if it even can't properly name the crate)

the solution: we need to provide some minimal backend templates and suggest using them in the documentation.

**Comment by gagdiez** [comment]
Maintaining different versions of same example is a complex task. Right now we have reorganized all our main examples so they're easier to strip out of unnecessary functions/components. For simplicity, we rather give a full project that can be easily downgraded, than one where the user needs to figure how to add a frontend.
