### ISSUE TITLE
Tests are Introduced in Z2H Tutorial Before Fixes to struct

### ISSUE THREAD

**Issue by idea404** [near/docs#1162]
Unit tests that make use the Smart Contract's `new` method are introduced [here](https://www.near-sdk.io/zero-to-hero/basics/hashing-and-unit-tests#write-a-regular-unit-test), while the changes to the `Contract` struct (adding the required `#[init]`) are introduced _after_ [here](https://www.near-sdk.io/zero-to-hero/basics/hashing-and-unit-tests#modifying-set_solution).

This complicates the code-along experience of the tutorial as learners would be left debugging for an error the tutorial does not go into. Proposed solution would be to either:

- Move this change before the unit tests are introduced
- Work through the bug with the learner/explain in the tutorial

**Comment by bucanero** [comment]
fixed in #1673
