### ISSUE TITLE
Document prefix usage for collections more clearly

### ISSUE THREAD

**Issue by austinabell** [near/docs#1166]
There should be a small section describing prefixes for storage collections and why they are important. Motivation based on question in zulip "I was wondering if anyone could explain the mechanics (why/deep-dive) we need to use unique prefixes in collections in the near-sdk? (e.g.: in RUST, LookupMap<K,V>::new(b"r" ... etc prefix = b"r")
Thanks!"

Quick answer:
So the storage layer of the NEAR runtime operates on key/value pairs which are bytes (&[u8]). When you are doing a lookup with LookupMap for example the byte string that will be used for the lookup will be a concatenation of the prefix and the key serialized to bytes (<prefix><serialized K>).

You need unique prefixes because there will be collisions and each structure will be reading, writing, and overwriting the same keys in storage, causing inconsistencies and unintended behaviour.

To document:
- What a prefix means and why it is necessary to be unique
- Basic usage with links to the trait `IntoStorageKey` rustdocs
- Usage with enums and more complicated data types: `BorshStorageKey` derive

**Comment by gagdiez** [comment]
This is now explained, with a whole example on how the prefix is then reflected in the state
