### ISSUE TITLE
UNIT Test fix

### ISSUE THREAD

**Issue by jim4067** [near/docs#1169]
Error when writing the `get_context` function

```rust      
.signer_account_id("bob_near".try_into().unwrap())
```

fixed it by using a std::String and changing the line to
```rust
.signer_account_id("bob_near".to_string().try_into().unwrap())
```
Does this deserve a PR?

**Comment by bucanero** [comment]
Fixed in https://github.com/near/sdk-docs/commit/0fdd780a14e030438ba12bb50a3db3083f35e872
