### ISSUE TITLE
[BUG] core dump instructions don't work on mac

### ISSUE THREAD

**Issue by janedegtiareva** [near/docs#117]
Running a node doc page: 
core dump instructions don't work on mac
(To enable coredump for docker, do echo '/tmp/core.%t.%e.%p' | sudo tee /proc/sys/kernel/core_pattern to modify system coredump location to /tmp.)

**Comment by amgando** [comment]
@janedegtiareva is this still valid?  or should we close?

**Comment by amgando** [comment]
closing since these instructions will be replaced by `nearup`
