### ISSUE TITLE
[BUG] White text against white background 

### ISSUE THREAD

**Issue by doriancrutcher** [near/docs#1176]
**Describe the bug** 🐞
search box text is white against the white search box background making the text difficult to see

**Expected behavior**
black text against a white background 

**Screenshots**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/59028579/187263979-e8fdeffd-66e8-4bd0-be02-86daf8ecd2cd.png">

**Location** 🎯
docs search box

**Comment by bucanero** [comment]
Fixed in https://github.com/near/docs/pull/1178
