### ISSUE TITLE
[BUG] error[E0599]: no function or associated item named `new` found for struct `Contract` in the current scope

### ISSUE THREAD

**Issue by url84t** [near/docs#1210]
**Describe the bug** 🐞
The "new" function does not exist in the code before the "Contract::new" function is called in the unit test shown on this page https://docs.near.org/tutorials/crosswords/basics/hashing-and-unit-tests#write-a-regular-unit-test

UPDATE:: it appears that the code example pulled from github is testing the "new" function (which is accurate for the final version of the testing code) it should test the "set_solution" function.  showing the final code from github is the cause of the issue.  

**Expected behavior**
I would expect the function to exist in the tutorial walk through code before we write a test for the function

**Screenshots**

**Location** 🎯
[code snippet found here](https://docs.near.org/tutorials/crosswords/basics/hashing-and-unit-tests#write-a-regular-unit-test)

**Comment by gagdiez** [comment]
the code and description seems correct to me, explaining that the code tests the get solution

**Comment by url84t** [comment]
The code is given as an example before the tutorial reaches that part of
the lesson.   It matches a little later but is not appropriate in that
context.   If you walk through the tutorial as someone who does not yet
know rust you will see the issue.  The refactoring comes later in the
tutorial

**Comment by gagdiez** [comment]
I see, thank you for reporting it! I'll reopen the issue and add a ticket to address it in a future sprint.
