### ISSUE TITLE
[near-sdk-rs] Document Attribute Macros

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1213]
View the current Rust docs here:
 [https://docs.rs/near-sdk/3.1.0/near_sdk/index.html#attributes](https://docs.rs/near-sdk/3.1.0/near_sdk/index.html#attributes)

*   [x] `ext_contract` provide description. When you click into it
*   [x] `near_bindgen` provide description and note this is very common and core to smart contract development. When you click into it
*   [ ] Extra credit for documenting other parts of this module that would benefit developers and might be frequently visited.

In the right sidebar under ***Epics***, click on the link for info on running Rust docs locally and good examples of documentation.

**Comment by thisisjoshford** [comment]
Closing this issue as we discuss this in the new anatomy of a contract 
https://docs.near.org/develop/contracts/anatomy

and also discuss ignore_state in the upgrading a contract section
https://docs.near.org/develop/upgrade

Please re-open this issue if you feel it is not fully resolved @frol @austinabell @mikedotexe
