### ISSUE TITLE
Misleading Links

### ISSUE THREAD

**Issue by miraclx** [near/docs#1249]
**Describe the bug** 🐞
Attempting “copy link” for any **Endpoint Root** URL in the [RPC Providers page](https://docs.near.org/api/rpc/providers) copies the wrong URL.

**Expected behavior**
The Endpoint URL should be copied.

**Meta**

https://github.com/near/docs/pull/1110 introduced a patch that routed these links back to the page itself, in order to avoid having broken links in CI.

However, these links aren't broken, they're just not your typical webpage.

As an alternative, we could use inline code blocks.

**Comment by bucanero** [comment]
I think the alternative of using `code blocks` could be useful, something like:

```
http://some.rpc.serv
```

**Comment by miraclx** [comment]
Unknown what the alternative would be for this:

https://github.com/near/docs/blob/672d39f6200495f46fdd3988ce374a14a8968425/docs/1.concepts/basics/networks.md?plain=1#L19

**Comment by bucanero** [comment]
those 2 URLs actually work and don't reply with a 404, so I think they could be linked properly.

**Comment by miraclx** [comment]
Yeah, I'd advocate for directly linking it. Wasn't sure why we went the other way in #1110.
