### ISSUE TITLE
[BUG] broken endpoint root links on https://docs.near.org/api/rpc/providers

### ISSUE THREAD

**Issue by anthony-near** [near/docs#1256]
**Describe the bug** 🐞
All Endpoint Root Links on the https://docs.near.org/api/rpc/providers page result in a 404 when clicked (links all go to https://docs.near.org/api/rpc/, which doesn't exist). 

**Expected behavior**
Links take you to the listed pages and not https://docs.near.org/api/rpc/

**Screenshots**

**Location** 🎯
[Live docs page with issues.](https://docs.near.org/api/rpc/providers) 
[Markdown in docs repo that should be updated.](https://github.com/near/docs/blob/master/docs/5.api/rpc/providers.md)

**Comment by miraclx** [comment]
Agreed, this is a duplicate of #1249.
