### ISSUE TITLE
[DOC] add Rust CLI to docs 🦀

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1269]
`near-cli-rs` is ready for prime time and should be added to docs.
https://github.com/near/near-cli-rs

**Comment by doriancrutcher** [comment]
Hello, 

I've created this markdown page for the near-rust-cli  for review. 

If this looks ok we can take next steps to add it to docs

https://hackmd.io/EuoA_Kt0Q4S_1X_i6uJ_-Q?view
