### ISSUE TITLE
[DOC] blockchain primitives primer

### ISSUE THREAD

**Issue by amgando** [near/docs#130]
**Is your feature request related to a problem? Please describe.**
We don't seem to have anything that surfaces and contextualizes nearcore primitives like `block` and `chunk`. 

**Describe the solution you'd like**
The nearcore source files are [well commented](https://github.com/nearprotocol/nearcore/blob/master/core/primitives/src/block.rs) but a primer would likely include a few links out to resources for understanding Merkle trees, Public Key Cryptography and other common knowledge among crypto enthusiasts.

**Additional context**
Here's an example of a clear, concise intro to Merkle Trees including basic mechanisms of use and justification for the technology

https://media.consensys.net/ever-wonder-how-merkle-trees-work-c2f8b7100ed3

**Comment by mattlockyer** [comment]
![image](https://user-images.githubusercontent.com/321340/82498677-40765680-9aa5-11ea-83fd-ff94f34f056b.png)

Is it not covered here?

Or were you hoping for more detail, long form writing and explanation of blockchain concepts?

**Comment by mattlockyer** [comment]
This looks like plenty to me:
![image](https://user-images.githubusercontent.com/321340/82498758-61d74280-9aa5-11ea-9621-d4496006e814.png)

**Comment by amgando** [comment]
ok, closing
