### ISSUE TITLE
[BUG] Incorrect link in Korean Docs

### ISSUE THREAD

**Issue by miguelmiguelasd** [near/docs#1387]
The cause of the issue is that some MDX components didn't consider the i18n path  (/ko in this case) when it's implemented: https://github.com/near/docs/blob/9d1d6efa4fef9b39b45e3c4a3858e41e45c96d39/docs/index.md?plain=1#L48   It's not hard to fix but I'll ask Damian to take a look as there're multiple components that we need to change I think.

**Comment by miguelmiguelasd** [comment]
It seems like en page is open when we click each icon in the Korean docs? Could you fix this problem?

**Comment by bucanero** [comment]
#1388
