### ISSUE TITLE
Ethers library not documented for Near BOS and not working [BUG] 

### ISSUE THREAD

**Issue by ademidun** [near/docs#1436]
**Describe the bug** 🐞
Following the [Ethers and Lido Tutorial](https://docs.near.org/bos/tutorial/ethers-js) for Near BOS.

When I call `Ethers.send("eth_requestAccounts", [])[0];` nothing happens.

Also,`Ethers` is not documented anywhere in the [BOS API](https://docs.near.org/bos/api/home)

**Expected behavior**
A metamask popup should come that asks me to connect my wallet to the dApp.

**Screenshots**

**Location** 🎯
You can find my source code here: https://near.social/#/mob.near/widget/WidgetSource?src=tomiwa1a1.near/widget/TransferNFT

**Comment by ademidun** [comment]
So I've solved it using `Web3Connect` which I found from one of the ETHGlobal Waterloo hackathon winners
https://near.org/near/widget/ComponentDetailsPage?src=a_liutiev.near/widget/button_web3connect

But Web3Connect is not documented anywhere, so what props does it accept? How can I get the result of the logged-in user?

**Comment by bucanero** [comment]
Hi @ademidun , thanks for the report! 👍 

We are working on adding more documentation around BOS, and all the tools and libraries that can be used with it. 
If by chance you want to improve any of our docs, all contributions from the community are welcome! 

About Ether-JS, you can check: https://docs.ethers.org/v5/
and I found this Web3connect repository: https://github.com/TotlePlatform/web3connect
