### ISSUE TITLE
Create a stand alone help landing page on docs.

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1457]
Problem:
Currently, at the end of each page, we have some resources that point to where someone can ask questions. This does not scale as when things need to be updated (as they do now) there are many places to do so. 

Solution:
Create a single source of truth that all external locations can point to or get data from.

- [ ] - landing site -> docs.near.org/help
- [ ] - should contain react component we can inject into other docs pages
- [ ] - [github.com/near/dx#help](https://github.com/near/dx#help) for starter info

**Comment by bucanero** [comment]
@thisisjoshford do you want me to take a look at this task?

**Comment by thisisjoshford** [comment]
> @thisisjoshford do you want me to take a look at this task?

Not right now, I'll let you know when this is ready for development.
