### ISSUE TITLE
[DOC] nearlib doesn't have comprehensive sdk documentation

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#146]
**Is your feature request related to a problem? Please describe.**

Nearlib should have a sdk doc that lists all the method available and how to use them.

**Comment by chadoh** [comment]
Related issue: https://github.com/near/devx/issues/99

**Comment by thisisjoshford** [comment]
`nearlib` is no longer used and was last updated over a year ago (https://www.npmjs.com/package/nearlib) Closing issue.
