### ISSUE TITLE
[157] missing mention of state.numVar in code

### ISSUE THREAD

**Issue by near-devex** [near/docs#1464]
**Describe the issue:** 
the doc said an example access state.numVar but there is no mention of that value in the code :/
## Info
**Reported by:** Unknown [(cuongdcdev@gmail.com)](mailto:cuongdcdev@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/IFPLADrBYSK8WTaJ4nqwR9EJT6cJVcl5ZjkOhAAh6zrnfb0FoOaAyASAxbWGF07WZaLHXM)
**Location:** VN
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/IFPLADrBYSK8WTaJ4nqwR9EJT6cJVcl5ZjkOhAAh6zrnfb0FoOaAyASAxbWGF07WZaLHXM?token=QorGXLNwfsfCgdelT17KugSmpIqQ6waUGr0stXhXtu4CqYjusXARvp9c6T0gxXJ9mL4SHH)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/IFPLADrBYSK8WTaJ4nqwR9EJT6cJVcl5ZjkOhAAh6zrnfb0FoOaAyASAxbWGF07WZaLHXM)
## Metadata
**browserName:** Chrome(115.0.0.0)
**userAgent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** Linux
**sessionDuration:** 108
**devicePixelRatio:** 1
**screenWidth:** 1920
**screenHeight:** 1200
**innerWidth:** 1920
**innerHeight:** 1083
**currentUrl:** https://docs.near.org/bos/api/state
**language:** vi-VN
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/FqpBT3hOMk7p2zOLsFeJB9WuXghW2dAdd5XimXF5KYLCeE0a5iZBmDh0u9YW8JuOkn4c69vhlvj.jpg)

**Comment by bucanero** [comment]
The example talks about the `profile` variable:

```
Here's an example of accessing a variable profile ...
```

Then the code snippet clearly shows `{state.profile}`
