### ISSUE TITLE
[158] encountering errors with @parcel/core during npm run build

### ISSUE THREAD

**Issue by near-dx** [near/docs#1465]
**Describe the issue:** 
Hello NEAR team!

I'm currently trying to build a NEAR project locally using `npx create-near-app@latest`. However, when I attempt to run `npm run build`, I encounter errors caused by @parcel/core.

Could you please assist me in resolving this issue?

Thank you!"
## Info
**Reported by:** Unknown [(cuhoangng@gmail.com)](mailto:cuhoangng@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/FZxgsa4SmjAZPeqYhklpwuxQmBXEZ05BdwmVdpLrJUJXKgmstuxwMmgtTcwpNf2Eq42w8c)
**Location:** VN
**Type:** 🚨 BUG
[Screenrecording link](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/DeYu3Aa3FrUZUEJV0gpp8jsbL14QIvkwaZqGQ4g0y7ajdzEUBNWE5gb51d8ot1lnMGXaaNSWFVF.webm)

[🔗 Open share link](https://app.gleap.io/share/FZxgsa4SmjAZPeqYhklpwuxQmBXEZ05BdwmVdpLrJUJXKgmstuxwMmgtTcwpNf2Eq42w8c?token=jMNYSBDVec48tB0HbR02JSyc3P5PrXS4KmWyqRHP449pNc0y4d9YTiWb4e6VKL6miAsMO4)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/FZxgsa4SmjAZPeqYhklpwuxQmBXEZ05BdwmVdpLrJUJXKgmstuxwMmgtTcwpNf2Eq42w8c)
## Metadata
**browserName:** Chrome(115.0.0.0)
**userAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** MacOS
**sessionDuration:** 1214
**devicePixelRatio:** 2
**screenWidth:** 1286
**screenHeight:** 698
**innerWidth:** 1280
**innerHeight:** 693
**currentUrl:** https://docs.near.org/develop/quickstart-guide
**language:** en-US
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/HGC4RDygSVbJ0WHrU6YlehXpNwcDphItXG6wJAetLHuxoWP1sqaBlBRGBhkHCtOPoYjEo0e7YgG.jpg)

**Comment by gagdiez** [comment]
we do not use parcel anymore on create-near-app
