### ISSUE TITLE
[161] confusing Create Account example

### ISSUE THREAD

**Issue by near-devex** [near/docs#1467]
**Describe the issue:** 
this make devs confused! this Create Account example here is for create sub account of the main account, it's not create top level account!
## Info
**Reported by:** Unknown [(cuongdcdev@gmail.com)](mailto:cuongdcdev@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/tStu3DokiCliS66XKg1bhSDfzEQBKkx4MRjXM8WXAbQ3LjMVH28Oq4ycDSSO8FB4wCmWSW)
**Location:** VN
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/tStu3DokiCliS66XKg1bhSDfzEQBKkx4MRjXM8WXAbQ3LjMVH28Oq4ycDSSO8FB4wCmWSW?token=wXXdT7BO68peYorSNMibEsNYwbJGduUWt7s41CdEIoTtYBV6lhbIRGvedUtkVBG4LhXTt9)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/tStu3DokiCliS66XKg1bhSDfzEQBKkx4MRjXM8WXAbQ3LjMVH28Oq4ycDSSO8FB4wCmWSW)
## Metadata
**browserName:** Chrome(116.0.0.0)
**userAgent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** Linux
**sessionDuration:** 1251
**devicePixelRatio:** 0.8999999761581421
**screenWidth:** 1920
**screenHeight:** 1200
**innerWidth:** 2133
**innerHeight:** 1203
**currentUrl:** https://docs.near.org/tools/near-api-js/account#get-account-balance
**language:** vi-VN
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/htfjG06TXza8PPJi5uNTN2Xn85Fup5yJEP4mOhOZKu7QPQArnTY3BdZ6e1jdyilUe5O8j1dhuHg.jpg)

**Comment by PiVortex** [comment]
This is not creating a sub-account, it is using the funds from one account to create another top-level account. A sub-account would look like sub.exapmle-account.testnet
