### ISSUE TITLE
[DOC] NEP-366 - documentation about meta transactions

### ISSUE THREAD

**Issue by PiVortex** [near/docs#1477]
**Is your feature request related to a problem? Please describe.**

Documentation on NEP-366 (meta transactions) is difficult to find 

**Describe the solution you'd like**

Either create documentation on NEP-366 or link the existing information somewhere in the docs. 
https://github.com/near/NEPs/blob/master/neps/nep-0366.md
https://github.com/near/pagoda-relayer-rs

**Additional context**

Adding to DevHub to see if anyone would like to create documentation on this.

**Comment by jakmeier** [comment]
FYI, I wrote a more technical behind-the-scenes view on meta transactions for nearcore developers: https://near.github.io/nearcore/architecture/how/meta-tx.html

**Comment by PiVortex** [comment]
Oh cool, I didn't even know these docs existed. Thanks!
