### ISSUE TITLE
[166] missing deposit amount parameter in Near.call

### ISSUE THREAD

**Issue by near-devex** [near/docs#1481]
**Descrivi il problema:** 
Hello i have used  near.call bos api below, but how to add deposit amount paraneter in it? I can't find an example to better explain.
Near.call(messagelist, "add_message", {
    text: state.greeting,
  });
## Info
**Reported by:** Unknown [(plutoplutone348@gmail.com)](mailto:plutoplutone348@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/l06OHlmo13gFJYiitI6M3xbG6C0A3jGWVOZKn6wLlZJW0DKVjP9ElNbDhhCuIIHw8GQW0d)
**Location:** FR
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/l06OHlmo13gFJYiitI6M3xbG6C0A3jGWVOZKn6wLlZJW0DKVjP9ElNbDhhCuIIHw8GQW0d?token=lk17m19tvbXpNvSDBdH1TdGpCLfr3xGoxUwfwiy3xKmAEqF5E8irkwnXvVBCw4xakoKBDE)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/l06OHlmo13gFJYiitI6M3xbG6C0A3jGWVOZKn6wLlZJW0DKVjP9ElNbDhhCuIIHw8GQW0d)
## Metadata
**browserName:** Chrome(111.0.5563.116)
**userAgent:** Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-A326B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/22.0 Chrome/111.0.5563.116 Mobile Safari/537.36
**browser:** Chrome
**systemName:** Android
**sessionDuration:** 120
**devicePixelRatio:** 2
**screenWidth:** 360
**screenHeight:** 800
**innerWidth:** 380
**innerHeight:** 456
**currentUrl:** https://docs.near.org/bos/api/near
**language:** it-IT
**mobile:** true
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/pFljQQHrZpYmDoTUyWfXa4J542Dk9jvh0LVKHf3HdNNdzqp5Np8Vf8sIny3Ilq0PXIMVpFOY1G9.jpg)

**Comment by gagdiez** [comment]
The documentation now clearly states there is a `deposit` attribute: https://docs.near.org/bos/api/near#nearcall
