### ISSUE TITLE
[168] missing dig docs

### ISSUE THREAD

**Issue by near-dx** [near/docs#1489]
**Describe the issue:** 
missing DIG docs
- we have about 24 DIG components created by `near` account but only two are documented. Noting this issue here as we should ensure these basic primitives are recorded in docs. Ultimately, we should have this documented in the near-discover-components repo and mirror to docs.near.org. (Following our "docs source of truth belong in the repo" methodology)  
## Info
**Reported by:** Unknown [(josh@near.org)](mailto:josh@near.org) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/ZWCAQLs7b4aTVs1jLfttLoQMduFjK6lr4oBEr1ZSlN1fZ6nzQ0pMWyWXAJdU85GfqvYGl9)
**Location:** VN
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/ZWCAQLs7b4aTVs1jLfttLoQMduFjK6lr4oBEr1ZSlN1fZ6nzQ0pMWyWXAJdU85GfqvYGl9?token=apGPiHUdSSIqym4zoJlyqe2lYcKbqKdq335Po0uifZwIGG4p73irHcnAIukEKKAjAAWpGI)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/ZWCAQLs7b4aTVs1jLfttLoQMduFjK6lr4oBEr1ZSlN1fZ6nzQ0pMWyWXAJdU85GfqvYGl9)
## Metadata
**browserName:** Chrome(116.0.0.0)
**userAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** MacOS
**sessionDuration:** 216
**devicePixelRatio:** 2
**screenWidth:** 1470
**screenHeight:** 956
**innerWidth:** 1284
**innerHeight:** 900
**currentUrl:** https://docs.near.org/bos/tutorial/ds-components
**language:** en-US
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/Fb9UGCp0JsEazZPfRqw3Q9Y8jP6BijpqTH7QznqYmDGPRezyk0M3OlWaS0adVQijH6WTUFrnAmB.jpg)

**Comment by charleslavon** [comment]
@bucanero perhaps we can quickly address this by reformatting [this section](https://docs.near.org/tutorials/near-components/ds-components#dig-components) to include a link to https://near.org/near/widget/DIG.OverviewPage

**Comment by charleslavon** [comment]
@bucanero we may also want to add a reference to this community library - https://www.uiisnear.xyz/
