### ISSUE TITLE
[177] switchboard documentation links 404 and switchboard oracle not working

### ISSUE THREAD

**Issue by near-dx** [near/docs#1511]
**Describe the issue:** 
Switchboard documentation links 404. Was also informed that the switchboard oracle in general does not work. We should investigate and determine if this is being supported.
## Info
**Reported by:** Unknown [(josh@near.org)](mailto:josh@near.org) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/sivkr5xQQp4Xy2VHrKT1ZukynHyixDgeYl677qchq69If1yOloRRDx3meGz5uF3F7Sixiu)
**Location:** US
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/sivkr5xQQp4Xy2VHrKT1ZukynHyixDgeYl677qchq69If1yOloRRDx3meGz5uF3F7Sixiu?token=wCJSLsc8Iw0PVq99TFu7FyoqdvfkZ9temKpbktgn3XuWkaOUhsKh0YQnI4smHGY4S0ArdQ)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/sivkr5xQQp4Xy2VHrKT1ZukynHyixDgeYl677qchq69If1yOloRRDx3meGz5uF3F7Sixiu)
## Metadata
**browserName:** Chrome(117.0.0.0)
**userAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** MacOS
**sessionDuration:** 13043
**devicePixelRatio:** 1
**screenWidth:** 3440
**screenHeight:** 1440
**innerWidth:** 1648
**innerHeight:** 1182
**currentUrl:** https://docs.near.org/develop/relevant-contracts/oracles
**language:** en-US
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/QwYUyq7zF5UNtypFOxIpDsvehqTA8NYek7RYNYEnrUzMplWLiroYmu6E3iJN85RZd3GsXliGn0J.jpg)

**Comment by gagdiez** [comment]
removed them
