### ISSUE TITLE
[BUG] Wrong link for Lido component 

### ISSUE THREAD

**Issue by PiVortex** [near/docs#1555]
**Describe the bug** 🐞
Briefly describe the issue you're experiencing.
The Lido component on the BOS for Ethereum developers docs links to the swap component 

**Expected behavior**
Describe what you were expecting to find.
It should link to the Lido component. 
https://near.org/near/widget/ComponentDetailsPage?src=zavodil.near/widget/Lido&tab=source

**Screenshots**
![image](https://github.com/near/docs/assets/124691791/b98d93a0-3350-447d-87d9-260f66eebdf7)
![image](https://github.com/near/docs/assets/124691791/60fa2760-81ff-4c37-9bea-53b14d6fae96)

**Location** 🎯
Please link to the page that you see this issue.
https://docs.near.org/bos/tutorial/ethers-js#examples

**Comment by flmel** [comment]
This has been fixed by #1556
