### ISSUE TITLE
[BUG] Search bar fails 

### ISSUE THREAD

**Issue by flmel** [near/docs#1569]
**Describe the bug** 🐞
When you click on the search bar and start typing in the docs webpage - the app crashes 

**Expected behavior**
The app shall operate normally 

**Screenshots**
[img](https://i.imgur.com/3aZF4Bn.png)

**Location** 🎯
https://docs.near.org

**Comment by bucanero** [comment]
@gagdiez  it seems the theme you added with the latest PR #1568 breaks the search bar on docs.near.org

**Comment by gagdiez** [comment]
fixed by #1571
