### ISSUE TITLE
[BUG] Fix broken link checker

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1577]
Running `./test-links.sh` script locally is broken and needs to be resolved.

- If the port is occupied when starting a server, it will not check the correct locally hosted site
- `429` error codes are abundant as too many requests to GH are made

**Comment by bucanero** [comment]
We haven't been using that `test-links.sh` script for a long time. We do have the "link checker" added to GitHub actions, but it has usually been neglected, and we need to review those reports to remove or update all current broken links.

I think this should be done after removing any pending Typedocs from our Docs, to simplify things.
