### ISSUE TITLE
[BUG] Rust contracts cross-contract calls documentation is outdated (near-sdk 4 introduced new API)

### ISSUE THREAD

**Issue by frol** [near/docs#1585]
**Describe the bug** 🐞

[The documentation](https://docs.near.org/sdk/rust/cross-contract/callbacks) features old API that is not compilable with near-sdk 4+ (released almost 2 years ago).

**Expected behavior**

The docs should be up-to-date and provide compilable examples.

**Screenshots**

<img width="745" alt="image" src="https://github.com/near/docs/assets/304265/cebc8833-de2a-40df-93a5-8ca7bef405a3">

This is the new API:

```
ext_ft::ext("ft_contract_address")
    .with_static_gas(BASE_GAS)
    .ft_transfer(caller, amount, memo)
```

See how it is used inside near-contract-standards: https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/fungible_token/core_impl.rs#L145

Also, docs should point out that if the function returns the promise, then it will delegate the return value and status of transaction execution, but if you return a unit type (`()` / "void" / "nothing"), then the Promise result will not influence the transaction status.

**Comment by gagdiez** [comment]
@garikbesson could you please check this?

**Comment by bucanero** [comment]
SDK docs were updated to sdk 4.0 here:
https://github.com/near/sdk-docs/commit/0fdd780a14e030438ba12bb50a3db3083f35e872
