### ISSUE TITLE
[184] Missing Dependency in Rust Quickstart

### ISSUE THREAD

**Issue by near-dx** [near/docs#1629]
**Describe the issue:** 
[https://docs.near.org/develop/contracts/quickstart] - When starting the project with Rust, there's a dependency missing `parity-secp256k1`.

I got this error: `no matching package named `parity-secp256k1` found`
**Summary:** 
Customer encountered error in Rust quickstart guide, needs assistance with missing dependency.
## Info
**Reported by:** Unknown [(wendersonpdas@gmail.com)](mailto:wendersonpdas@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/hoZSKG5qzkW09OYqz1XJM8xbwfsWKi8s2bS8i6fR2WrWlNpjSsX2wdZSw5RqSe5QZIkpo9)
**Location:** BR
**Type:** 🚨 BUG

[🔗 Open share link](https://app.gleap.io/share/hoZSKG5qzkW09OYqz1XJM8xbwfsWKi8s2bS8i6fR2WrWlNpjSsX2wdZSw5RqSe5QZIkpo9?token=bnUjn0aSxBxjLFjBD8rNH1NwzvAG6Fmvr6v7ARZSwZvZPHXnZ7ub6C1xvsKu33hxVCl7da)
[🌍 Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/hoZSKG5qzkW09OYqz1XJM8xbwfsWKi8s2bS8i6fR2WrWlNpjSsX2wdZSw5RqSe5QZIkpo9)
## Metadata
**browserName:** Chrome(120.0.0.0)
**userAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** MacOS
**sessionDuration:** 656
**devicePixelRatio:** 1
**screenWidth:** 5120
**screenHeight:** 1440
**innerWidth:** 1643
**innerHeight:** 1328
**currentUrl:** https://docs.near.org/develop/contracts/quickstart
**language:** en-US
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/9dwqwYeF6sEhC1J75UPtik6IznPb8sbiSWZzS149N5NN0LhfYBwqKr0zALPYPizyzWD5xhWZRqY.jpg)

**Comment by near-dx** [comment]
Internal note 📝: Customer encountered error in Rust quickstart guide, needs assistance with missing dependency.

**Comment by gagdiez** [comment]
This sound like a user-specific bug, and not something general for us to fix. Will keep it open for now, but close if nobody else reports something similar
