### ISSUE TITLE
🔹[EPIC] Chain Signatures API docs

### ISSUE THREAD

**Issue by bucanero** [near/docs#1677]
### Description

Documentation for chain signatures API. (big chunk of the Account Abstraction work)

---

### Goal

We’d like to have a few documents for people to use it covering:
- What it is
- How to use it (wallet client & smart contract)
- What it’s useful for
- Some worked examples from end to end

---

### Resources

(Relevant documentation, Figma links, and other reference material)

- [The why of chain signatures](https://github.com/near/NEPs/issues/503)
- [The proposed wallet API for signing things across chains](https://github.com/near/near-fastauth-wallet/blob/dmd/chain_sig_docs/docs/chain_signature_api.org)
- [Our trove of product documents](https://drive.google.com/drive/folders/1UKpZh_tEZCrdya7mW2UzL_s5XixzkOvX)
- [How this can be used for cross chain swaps](https://docs.google.com/presentation/d/1qNhLlIavDJxgnlt04Ma8z2tAQutG1a0CveWK1VoTzRI/edit#slide=id.p)
- [How this can be used for cross chain lending](https://docs.google.com/document/d/1OMBAQQ_F5yGtG_oGIwmStCSMOj36kZtLsrdD8JlZ8GA/edit)

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1678
- [ ] https://github.com/near/docs/issues/1679
- [ ] https://github.com/near/docs/issues/1680
- [ ] https://github.com/near/docs/issues/1681
```

**Comment by bucanero** [comment]
Req. by @DavidM-D

**Comment by DavidM-D** [comment]
We're releasing on mainnet on the 31st of March, but it'd be great to gradually release docs for people who are building on testnet.
