### ISSUE TITLE
🔹[EPIC] Documentation for Multi-Chain Relayer Service

### ISSUE THREAD

**Issue by bucanero** [near/docs#1696]
### Description

Create technical documentation for the new Multichain Relayer service. This documentation should cover the two core components

- (1) Multi-Chain Gas Station Contract
-  (2) Multi-Chain Relayer Server

---

### Goal

Articles needed:
- Basic documentation that covers the different aspects of the Multichain Relayer service and how developers can leverage this product.

POCs: Anthony Witterman, Firat Sertgoz, Gautham Ravi

---

### Resources

(Relevant documentation, Figma links, and other reference material)

- Technical Design Doc -->  https://docs.google.com/document/d/1ZvfiVDXSykYsdH8v816G-V5OizAUtpw9WAh1ihwz908/edit#heading=h.bjcoqk88m3iy

---

```[tasklist]
### Related Issues
- [ ] https://github.com/near/docs/issues/1712
- [ ] https://github.com/near/docs/issues/1741
- [ ] https://github.com/near/docs/issues/1742
- [ ] https://github.com/near/docs/issues/1804
```

**Comment by ravigautham** [comment]
We will need this to be completed to accompany the documentation for the larger launch of Multichain products (e.g. Chain Signatures etc). @bucanero

**Comment by bucanero** [comment]
Update: we are aiming to have a "v1" of the relayer service docs by Feb-27 (EthDenver)
