### ISSUE TITLE
[META] Add product tracking events

### ISSUE THREAD

**Issue by charleslavon** [near/docs#1699]
**Is your feature request related to a problem? Please describe.**
Product analytics was recently added into docs to track page views. Let's add improve our ability to understand anonymized user journeys by tracking the following events

```[tasklist]
### Tasks
- [ ] wallet-connected
- [ ] wallet-logout
- [ ] mouseover
- [ ] touchstart
- [ ] click
```

**Comment by s-n-park** [comment]
CC: @xuan-ytr this is the backlog ticket for adding clicks to Docs.near.org

**Comment by s-n-park** [comment]
Given that click through search rate is an OKR, would it be possible to prioritize adding this tracking?
![image](https://github.com/near/docs/assets/146785798/7cef53af-5d0e-436e-837c-d25d7aeb5d68)

**Comment by thisisjoshford** [comment]
@s-n-park can you connect with @gagdiez to scope out what is needed for this ticket to be completed?

**Comment by s-n-park** [comment]
I believe that @gagdiez already added this in since it's showing up in Algolia:

![image](https://github.com/near/docs/assets/146785798/3666d30d-5840-48f2-ae88-4a6154d0ffc4)

Have been adding to regular metrics reporting, so closing this out as done! :)
