### ISSUE TITLE
When transaction is going to be bounced

### ISSUE THREAD

**Issue by nearmax** [near/docs#170]
We need an exhaustive documentation that explains all the stages when transaction can be rejected, under what conditions it can be rejected, and what error message we are going to observe through RPC when this happens. This should take into account the storage and the account name rent. Note, it is crucial that this documentation is exhaustive, because our partners will heavily rely on its exhaustiveness.

Transaction currently can be rejected in multiple places:
* Before it is included in the mempool;
* After it is pulled from the mempool;
* When chunk is executed.

@evgenykuzyakov do you remember any other places where we bounce transactions?

**Comment by nearmax** [comment]
Assigning to @amgando to create such documentation and @fckt to provide the answers.

**Comment by amgando** [comment]
@fckt and @nearmax can we start right here with a simple outline of this content?  also what does success look like?  is it a single page or something more?

**Comment by bowenwang1996** [comment]
I don't think length of the content should be a concern. It works as long as it exhaustively lists and explains all the situations.

**Comment by nearmax** [comment]
I would let @fckt  (or @bowenwang1996 if he wants) to outline it. The success is when we have all cases 100%, independently on the size.

**Comment by nearmax** [comment]
@fckt please estimate how much you would need then ask @amgando how much time he would need to shape your stuff into documentation and set the "estimate" for this issue in ZenHub.

**Comment by nearmax** [comment]
We also need to add explanation on what code error we will observe through RPC when this will be happening.

**Comment by amgando** [comment]
@nearmax hoping to push this up before the weekend for feedback so we can publish first thing next week

**Comment by potatodepaulo** [comment]
@chain-police I closed this thinking it was done, it turns out it's not. Can you take a look at: https://github.com/near/docs/pull/248 and add anything missing please?

**Comment by gagdiez** [comment]
@nearmax @thisisjoshford @amgando Should we place this in nomicon.io ? We see that there was a branch that is now closed. If still relevant, lets open a new issue.
