### ISSUE TITLE
Create full example about multi-chain relayer + gas station

### ISSUE THREAD

**Issue by bucanero** [near/docs#1742]
Add examples that show how developers can leverage both the gas contract and the relayer server to relay cross-chain transactions

**Comment by thisisjoshford** [comment]
@ravigautham @anthony-near is the multichain-gas-relayer service ready for us to start working on this ticket?

**Comment by thisisjoshford** [comment]
> no. I will let you know when it is. Should be ready by Wednesday at the latest

awesome! tysm for the speedy reply!

**Comment by anthony-near** [comment]
Instructions on how to generate an example are here: https://github.com/near/multichain-relayer-server/blob/feature/MVP_ethers/integration_tests/README.md. I will continue testing tomorrow.

**Comment by thisisjoshford** [comment]
@bucanero ready for development here :)
