### ISSUE TITLE
[RS-SDK5] Migrate Self Update & Migration - https://docs.near.org/tutorials/examples/update-contract-migrate-state

### ISSUE THREAD

**Issue by gagdiez** [near/docs#1752]

**Comment by dj8yfo** [comment]
@gagdiez , @bucanero  i'd be glad to take this one.

**Comment by gagdiez** [comment]
amazing!

**Comment by dj8yfo** [comment]
started work on https://github.com/near-examples/update-migrate-rust/pull/1 , 
expecting some interruptions from IRL. 
will resume and finish asap
