### ISSUE TITLE
[198] Assistance Needed with Wrong Address

### ISSUE THREAD

**Issue by near-dx** [near/docs#1782]
**Title:** 
Assistance Needed with Wrong Address
**Description:** 
sended wrong adress NEAR can u help please? 
txHash - GJ3UxxBGE5TkysqNhdNR4x46ETwbNSqyjVuWuzfGr7yA
**Summary:** 
Customer needs help with wrong address sent. Requesting assistance for resolving the issue.
## Info
**Reported by:** Guest [(muxac13@gmail.com)](mailto:muxac13@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/qBnBZktZTHpjim5VoWJiMNhpo5u6SO96V7f716npE5UJNrxzYn2wZ52GucfpfYbTOJpAbi)
**Location:** UA
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/qBnBZktZTHpjim5VoWJiMNhpo5u6SO96V7f716npE5UJNrxzYn2wZ52GucfpfYbTOJpAbi?token=RqLFiV6JJYEdEMIuXt5SmKMdnPWkkiN46e0rzdnByaeDfdvNoXnUW6XiKsruqDhl2wK4WH)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/qBnBZktZTHpjim5VoWJiMNhpo5u6SO96V7f716npE5UJNrxzYn2wZ52GucfpfYbTOJpAbi)
## Metadata
**browserName:** Chrome(122.0.0.0)
**userAgent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** Windows
**sessionDuration:** 40
**devicePixelRatio:** 1
**screenWidth:** 1920
**screenHeight:** 1080
**innerWidth:** 1920
**innerHeight:** 919
**currentUrl:** https://docs.near.org/concepts/basics/transactions/overview
**language:** ru-RU
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/nWyhalfp56Obb4CGg4j2QSKJkGREtwDgzpAyd25CSRs2aNqpHvMDcOojoBoNwGyZG3PDeKyupxk.jpg)

**Comment by near-dx** [comment]
Internal note 📝: Customer needs help with wrong address sent. Requesting assistance for resolving the issue.

**Comment by bucanero** [comment]
Hi, you should contact your Wallet customer support to check if they can help with your issue.
Near Docs is only a site with technical documentation for blockchain developers.
