### ISSUE TITLE
[BUG] Multichain Relayer Server prints "hello world"

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1784]
**Describe the bug** 🐞
When I click on the highlighted link on https://docs.near.org/develop/relayers/multichain-server:

<img width="1326" alt="Screenshot 2024-03-04 at 7 29 48 PM" src="https://github.com/near/docs/assets/1042667/064b7f3d-44fe-420c-a51a-bb3e1b1ad6b5">

It leads to a repo that prints "hello world"
https://github.com/near/multichain-relayer-server/blob/b0138d8f64d53ea4a9380082787dde6ff32df331/src/main.rs#L1-L3

There are a couple of branches in there, perhaps one of them is in progress and then docs can navigate to an updated branch.

**Comment by bucanero** [comment]
thanks @mikedotexe , I'll check with the team to be sure which branch should be referenced.

**Comment by mikedotexe** [comment]
I don't think this is blocked, as I've seen a pull request come in lately so that the app no longer prints "hello world" and has more relevant code. I'm not sure if that's working as intended quite yet, but wanted to give that update:
https://github.com/near/multichain-relayer-server/blob/138cc50fc97c59ee86e7543c1bc6b553bfb6629e/src/main.rs

**Comment by bucanero** [comment]
I confirmed with the team, they merged a few PRs and the latest code is now on the main branch.

They also added a note on the repo's Readme to inform users that the relayer is not production-ready yet. They will remove that note once the production release is out.

I'm closing this issue as we can keep the current link to the master branch.
