### ISSUE TITLE
Remove deprecated message above recommended RPC method

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1798]
Small 1-liner to remove the deprecated header, must be leftover from a while ago I imagine.

<img width="1121" alt="Screenshot 2024-03-08 at 10 06 08 AM" src="https://github.com/near/docs/assets/1042667/2f0720c1-4f42-4b24-883d-d8646bd33c15">

This is important because of recent developments where we want to push devs to use that the async function in order to avoid some of the UX throes of shard congestion.

https://twitter.com/BowenWang18/status/1765956174292394228

**Comment by bucanero** [comment]
hi @mikedotexe 

I'm happy to update, but the `deprecated` tag was added by @telezhnaya for the 1.37 release. Here's the original PR: https://github.com/near/docs/pull/1564

I'd suggest checking with Olga or the nearcore team about it. (tagging @bowenwang1996 just in case he can provide some additional details)

**Comment by telezhnaya** [comment]
It's on me, I'll review and update this page soon.

It's not a leftover, we do have a new method `send_tx`.
But I need to think how it's better to promote this new method
