### ISSUE TITLE
Instructions to add specific public key to an account (NEAR CLI JS)

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1800]
Let's say I want to create `docs.mike.testnet` and have a specific public key in mind for that account.

I'm unsure of the best flow for this given the new NEAR CLI commands.

Right now the `create-account` method will automatically generate a keypair and place it in `~/.near-credentials/testnet/new-account.mike.testnet.json`

<img width="937" alt="Screenshot 2024-03-08 at 1 55 35 PM" src="https://github.com/near/docs/assets/1042667/6c498962-7aa5-439d-a9b4-53ffa9d8a254">

Right now I'm just making this `ifyouknowabetterway.json` file so I can save the new key pair somewhere, and then grab the pubkey and add it as a full access key to my new account. Then I think I'd manually change `~/.near-credentials/testnet/new-account.mike.testnet.json`, replacing the private and public keys with what's in `~/.near-credentials/testnet/ifyouknowabetterway.json`

It's quite possible I'm doing this a silly way. 
This ticket is created not to fix NEAR CLI, but to give BD partners and NEAR builders some basic instructions so they don't have to feel the burden of figuring out the use case.

**Comment by gagdiez** [comment]
1. you can create the account passing a specific publicKey:

`near create-account <new-account-id.testnet> --publicKey ed25519:...`

2. you can then add the credentials

`near add-credentials <new-account-id.testnet> --privateKey ed25519:...`

will see to add this to the docs
