### ISSUE TITLE
[DOC] Update `SignedDelegate` docs for standard relayers

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1805]
- @gagdiez identified that `SignedDelegate` is not working in `near-api-js` -> https://github.com/near/near-api-js/issues/1313

- Fix has been created and awaiting merge -> https://github.com/near/near-api-js/pull/1314

- Once merged, update docs to reflect these changes

**Comment by gagdiez** [comment]
PR: https://github.com/near/docs/pull/1820
