### ISSUE TITLE
[DOC] Update and improve Data Availability docs

### ISSUE THREAD

**Issue by bucanero** [near/docs#1808]
As discussed with @ravigautham , we plan to update the DA docs. 

Don Dall will be drafting additional information in the next weeks.
```[tasklist]
### Tasks
- [ ] https://github.com/near/docs/pull/1818
```

**Comment by thisisjoshford** [comment]
@ravigautham @dndll do you have next steps here for this?

**Comment by thisisjoshford** [comment]
@ravigautham @dndll closing this issue, please feel free to reopen if there are more action items here.
