### ISSUE TITLE
[META] enhance onboarding experience for docs with increasing levels of detail

### ISSUE THREAD

**Issue by amgando** [near/docs#181]
**Is your feature request related to a problem? Please describe.**
- the landing page for docs is highly rated (via anecdote)
- clicking "Contribute" we hit a wall of text (same with all other role-based entry points)

**Describe the solution you'd like**
- apply the JS SDK Guides pattern of TOC + start -> steps -> stop
- for example, 
  - click "Contribute"
  - see a visual (icon list with text) representation of areas to contribute (ie. NEAR Wallet, NEAR Explorer, etc)
  - click for details
  - see a stepwise walkthrough like JS SDK Guides (including 2 min video summaries)

**Comment by amgando** [comment]
@Patrick1904 see here as per our discussion

**Comment by thisisjoshford** [comment]
PR https://github.com/near/docs/pull/602 addresses a lot of this but is an ongoing process. Cleaning up issues in docs and closing this one in favor of adding new smaller ticket items for docs enhancements.
