### ISSUE TITLE
[203] Clarification on NEAR's MPC Service

### ISSUE THREAD

**Issue by near-dx** [near/docs#1817]
**Title:** 
Clarification on NEAR's MPC Service
**Description:** 
Instead of "NEAR's MPC service allows for nodes to safely join and leave, without needing to re-derive a master key" would it be more clear to say "However, each node in NEAR's MPC service contains one piece of a master key for a given account, and supports nodes entering and leaving without  needing to re-derive a master key".   There is still a gap in explaining "how" Near's MPC can avoid re-deriving a master key, but is this language accurate and more helpful? 
**Summary:** 
Customer is seeking clarification on the explanation of NEAR's MPC service. Consider providing more detailed information on how it avoids re-deriving a master key.
## Info
**Reported by:** charles [(charles@near.org)](mailto:charles@near.org) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/Ovru0rBDA5iyaq6IMbQLvKWJTv4XTEPsEU4oLwl0nJOj2oGULQtyfaQjHYFxQIcK1KhmQd)
**Location:** US
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/Ovru0rBDA5iyaq6IMbQLvKWJTv4XTEPsEU4oLwl0nJOj2oGULQtyfaQjHYFxQIcK1KhmQd?token=DrUpRN9daQc0W8GeIkK1tYNpHBsPQCrnQxwel6YyntgTZYvKHhhrWQTyXnnYWjLm6hkQjp)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/Ovru0rBDA5iyaq6IMbQLvKWJTv4XTEPsEU4oLwl0nJOj2oGULQtyfaQjHYFxQIcK1KhmQd)
## Metadata
**browserName:** Chrome(122.0.0.0)
**userAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** MacOS
**sessionDuration:** 7923
**devicePixelRatio:** 2
**screenWidth:** 1512
**screenHeight:** 982
**innerWidth:** 1369
**innerHeight:** 823
**currentUrl:** https://docs.near.org/concepts/abstraction/chain-signatures
**language:** en-US
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/rLr1aIpommTTn4uH5VoR62IM0tTJ6a85PbmLoyT773DSCBovzcP8GRNb5lwSSP5NTXEhJn4oh2G.jpg)

**Comment by gagdiez** [comment]
but they do not contain a piece of the master key, as the text explain, they have a `signature share`.

No master key is derived at any point, otherwise an adversarial node could leave and join iteratively until getting enough pieces of the master key to reconstruct it.

At least this was my understanding
