### ISSUE TITLE
[META] external links should be distinct from internal links

### ISSUE THREAD

**Issue by amgando** [near/docs#182]
**Describe the bug**
Today it's difficult to know whether clicking a link will take me out of the documentation or deeper into the documentation

**Expected behavior**
It would be better to have some visual indication of external links

**Screenshots**
several external links on this page
![image](https://user-images.githubusercontent.com/24913/73369321-324fc080-4291-11ea-9453-e1dff3dc9091.png)

example of external link indicator
![image](https://user-images.githubusercontent.com/24913/73369369-4398cd00-4291-11ea-8f2e-83fa6f3dfacc.png)

**:pencil: Location**
Here's one page where this would make a difference to readers
https://docs.nearprotocol.com/docs/contribution/contribution-overview

**Comment by gagdiez** [comment]
+1 on this issue. @bucanero and @gagdiez will take a look into how to apply this in both current and new docs.
