### ISSUE TITLE
Chain Signature use cases page

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1827]
I'm creating the presentation for chain signatures today and reviewing the docs here: https://docs.near.org/concepts/abstraction/signatures/use-cases#trade-blockchain-assets-without-transactions

Regarding "Trade Blockchain assets without transactions" I'm not sure folks will understand this. There are transactions happening on different chains, but you don't have to have separate browser extension wallets with seed phrases and passwords… the works.

Suggestion to massage the verbiage here so that folks are clear that an MPC service is signing a transaction that is broadcast to another blockchain's RPC/API

**Comment by bucanero** [comment]
@mikedotexe could you take a look at the PR https://github.com/near/docs/pull/1853 , and share your feedback if the use case is clear? thanks!
