### ISSUE TITLE
[DOC] Suggestion to modify chain signature public key fetching

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1828]
**Is your feature request related to a problem? Please describe.**
In the README for `mpc-recovery` I see we're suggesting that the client knows the public key of the MPC service:

<img width="1119" alt="Screenshot 2024-03-20 at 8 46 38 AM" src="https://github.com/near/docs/assets/1042667/d05dd56a-7093-4890-8e80-6a0421a64657">

https://github.com/near/mpc-recovery/?tab=readme-ov-file#mpc-public-key

And then in the docs I was seeing we recommend fetching the public key directly from the contract:

<img width="1291" alt="Screenshot 2024-03-20 at 8 44 08 AM" src="https://github.com/near/docs/assets/1042667/d359795c-ca9e-4552-934f-f6bb94ff803e">

https://docs.near.org/abstraction/chain-signatures#1-deriving-the-foreign-address

**Describe the solution you'd like**
If I'm understanding the reasons and security correctly, it seems that we'll want to provide the public key in docs, which for testnet I believe is:

`secp256k1:4HFcTSodRLVCGNVcGc4Mf2fwBBBxv9jxkGdiW2S2CA1y6UpVVRWKj6RX7d7TDt65k2Bj3w9FU4BGtt43ZvuhCnNt`

**Additional context**
Another note: I was unable to get to this landing page (where I can see the left sidebar showing **Chain Abstraction Services**) except through searching or through a link under https://docs.near.org/concepts/abstraction/chain-signatures#derivation-paths-one-account-multiple-chains

It seems that we'll want to provide a path where an end user can arrive on the docs site and navigate to this area.

**Comment by gagdiez** [comment]
will harcode it
