### ISSUE TITLE
[BUG] Gif on README out of date (in nearcore as well)

### ISSUE THREAD

**Issue by potatodepaulo** [near/docs#185]
**Describe the bug**
The gifs that demonstrate our tools across all repos are out of date

**Expected behavior**
Updated gif of current studio OR local workflow OR remove it until we port to GitPod.

**Screenshots**
<img width="964" alt="Screen Shot 2020-02-04 at 2 51 41 PM" src="https://user-images.githubusercontent.com/6679554/73771849-e18f0a80-475d-11ea-8bc6-678059869b5f.png">

**:pencil: Location**
https://github.com/nearprotocol/docs/blob/master/README.md
https://github.com/nearprotocol/nearcore/blob/master/README.md

**Comment by amgando** [comment]
i think this is done, right, @potatodepaulo ?
