### ISSUE TITLE
[DOC] Create README template to be used for all `near` repos

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1860]

**Comment by bucanero** [comment]
Proposed github repo template:

https://github.com/near-examples/readme-template

**Comment by bucanero** [comment]
@thisisjoshford @gagdiez, what do you think about this Readme template?

**Comment by gagdiez** [comment]
LGTM for big projects (QueryAPI, DA, Indexer, etc), and for small examples on docs we can follow [the convention we are using now](https://github.com/near-examples/hello-near-examples), which is simpler since the repos are also simpler
