### ISSUE TITLE
[DOC] Create article about NFT Keys smart contract

### ISSUE THREAD

**Issue by bucanero** [near/docs#1894]
Based on @encody @ravigautham request, we need to create a new article for the "NFT Keys" smart contract

### Article details

- Contract repo: https://github.com/near/multichain-gas-station-contract/tree/feat/nft-key-integration/nft_key
- "NFT Keys" article should live on its own as another section under `Chain Abstraction` since it is closely related to the Chain Signature product
- The article needs to provide:
  -  an overview of the functionality of the contract
  - a `Use Cases` section towards the bottom of the article that puts forward some ideas of how the contract could be used

#### Notes

Regarding the `use cases` section, @ravigautham will be helping to draft ideas for it.

> This article should be published before we launch Chain Signatures on mainnet

**Comment by ravigautham** [comment]
### Use Case Ideas

The NFT key contract makes the ownership of remote accounts both provable and transferrable. This new paradigm will allow for the creation of new end-user experience that leverage provable and transferrable remote accounts as a core primitive. 

(Disclaimer: The below ideas are just initial concepts, they are not fully fledged or thought out solutions. 

### Remote Account Marketplace

NFT Keys enable users to engage in buying, selling, and trading remote accounts within a marketplace-style application. For instance, User A, possessing a set of remote accounts with value and history, can mint an NFT key and list these accounts for sale on the marketplace. Potential buyers, like User B, can browse the value of User A's accounts and choose to make a purchase. If User B decides to proceed, they would simply need to acquire ownership of the original NFT key from User A in exchange for payment, such as in $NEAR. Once the transaction is completed, ownership of the accounts transfers to User B.

### Bridgeless Multi-Chain DEX

By combining Chain Signatures with NFT Keys, we can create a Multichain DEX without the need for bridging. Here's how it works: Users wishing to swap asset A for asset B would initiate the swap on the DEX. Supported by liquidity providers (Automated Market Makers) across multiple chains, the DEX facilitates these swaps. A user proposes the swap, specifying asset A in remote account X for asset B in remote account Y. The liquidity provider receives asset A from the user and sends the equivalent amount of asset B to a newly created remote account Y, along with a minted NFT key. The NFT key is then sent to the user, completing the swap. Although liquidity providers still need to leverage bridging for settling assets between different pools, users of this exchange type are exposed to reduced bridge risk.

**Comment by ravigautham** [comment]
@encody @bucanero Added some thoughts on use cases above ^ feel free to edit or add additional thoughts.
