### ISSUE TITLE
Improve Algolia search results

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#1941]
## Goal

How might we improve search results for common queries on docs.near.org and near.org ?  Potentially by setting [custom redirect rules](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/redirects) for the [top 20-ish searches ](https://dashboard.algolia.com/apps/B6PI9UKKJT/analytics/searches/prod_near-social-feed?from=2024-05-07&to=2024-05-13)  with better results such as pages [from nearcatalog](https://near.org/applications) or directly to [defi options](https://dev.near.org/nearcatalog.near/widget/Index?cat=defi) for a search query such as `marketplaces`

## Issue
Algolia search sometimes doesn't return the best results based on user search. For example, if a user searches for `NFT` the ideal result would have "Non-Fungible Token" section at the top but it's the sixth option:

<img width="645" alt="Screenshot 2024-04-29 at 2 36 28 PM" src="https://github.com/near/docs/assets/58483342/d6754976-b1ef-402b-a430-119059b63226">

## Potential Solution / Additional Context

- Algolia indexer needs header optimization to return more meaningful results. 
- Review Algolia docs to see how we can improve the automatic ranking or implement custom ranking. 

## Resources

- [Algolia search log](https://dashboard.algolia.com/apps/0LUM67N2P2/analytics/searches/near?from=2024-04-22&to=2024-04-28) (From Algolia dashboard -> Search > Observe > Analytics)
- [Algolia Ranking Docs](https://www.algolia.com/doc/guides/managing-results/relevance-overview/in-depth/defining-relevance/#ranking-putting-the-best-at-the-top)

```[tasklist]
### Tasks
- [ ] https://github.com/near/docs/issues/2000
- [ ] https://github.com/near/docs/issues/1999
- [ ] https://github.com/near/docs/issues/2001
- [ ] https://github.com/near/docs/issues/2002
```

**Comment by s-n-park** [comment]
FYI: @jackson-harris-iii , @shelegdmitriy - on near.org some of the top search terms via the topnav were “ref-finance” and “sweat-economy” yet surprisingly these don’t show up under apps.

From this [thread](https://pagodaplatform.slack.com/archives/C0559BC3WBZ/p1712600869976959)

**Comment by shelegdmitriy** [comment]
Well, this [custom redirect rules](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/redirects) feature is exactly what we need but it's not free. But still we can use a free trial to check how it works and then decide do we really want to pay for this feature or not. @thisisjoshford @charleslavon can we request a free trial? I believe it's worth to do from Monday to have a chance to test it properly. WDYT?

**Comment by charleslavon** [comment]
@shelegdmitriy Rules should already be enabled for the near.org algolia project. Let me get you access.

**Comment by shelegdmitriy** [comment]
During testing the custom rules & redirects feature, I could only configure a rule for query "sweat" or "sweet" to point to nearcatalog app. Redirects so far as a rule (to point directly to the https://dev.near.org/nearcatalog.near/widget/Index?id=sweat-economy page on nearcatalog) doesn't work. Maybe if we could somehow index the nearcatalog apps then we would solve this in a very easy way I think. This is something I'm about to take a look at.

But still, custom rules works perfect if there is a item in index. Let me explain a bit: if I have a `sheleg_meteor.near` account I can create a rule to propose a `near` account at first place instead of my real account. This means we can improve our docs.near.org by using re-ranking or rules.

Let me know your thoughts @charleslavon @thisisjoshford

**Comment by shelegdmitriy** [comment]
A small update so far: there is a new index [test-nearcatalog-index](https://dashboard.algolia.com/apps/B6PI9UKKJT/explorer/browse/test-near-catalog-index?query=sweat&searchMode=search) with all the data which presented on this [page](https://near.org/nearcatalog.near/widget/Index). My next step is testing and adding this into the main index

**Comment by charleslavon** [comment]
> A small update so far: there is a new index [test-nearcatalog-index](https://dashboard.algolia.com/apps/B6PI9UKKJT/explorer/browse/test-near-catalog-index?query=sweat&searchMode=search) with all the data which presented on this [page](https://near.org/nearcatalog.near/widget/Index). My next step is testing and adding this into the main index

awesome. Did you create this manually?

**Comment by shelegdmitriy** [comment]
Maybe it's worth to split this issue into two subtasks? One for dev.near.org and another for docs.near.org?
