### ISSUE TITLE
MPC: add root public key for clients to hardcode

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#1968]
We're ramping up a member of Proximity, and he was having a hard time finding the MPC root key.

I pulled `master` and searched globally but couldn't find it. So this issue is to make sure we include:

`secp256k1:4HFcTSodRLVCGNVcGc4Mf2fwBBBxv9jxkGdiW2S2CA1y6UpVVRWKj6RX7d7TDt65k2Bj3w9FU4BGtt43ZvuhCnNt`

So that folks who are creating clients are sure to hardcode it as suggested

**Comment by gagdiez** [comment]
Indeed, this is important, moreover since the key has changed for the new contract:

`secp256k1:4NfTiv3UsGahebgTaHyD9vF8KYKMBnfd6kh94mK6xv8fGBiJB8TBtFMP5WWXz6B89Ac1fbpzPwAvoyQebemHFwx3`
