### ISSUE TITLE
[DOC] add collection of "best of" resources for our key technology and design areas

### ISSUE THREAD

**Issue by amgando** [near/docs#197]
**Is your feature request related to a problem? Please describe.**
we want curated "best of" content for our tech stack including intros to AssemblyScript (TypeScript is also useful here), Rust, building web apps, designing blockchain applications, etc.

**Describe the solution you'd like**
a single page in the docs with a few of these key resources that is referenced throughout the docs seems like a good idea

the page can be located under the `basics` section of the docs

**Comment by thisisjoshford** [comment]
The "essential resources" on the [docs landing page](https://docs.near.org/docs/develop/basics/getting-started) seems to address this issue :)
