### ISSUE TITLE
[DOC] Super confusing getting started docs

### ISSUE THREAD

**Issue by miraclx** [near/docs#1980]
Not sure who to cc on this, but someone just brought this to my attention.

The getting started guide is super inconsistent. (at least the Rust side of things)

Live: https://docs.near.org/build/smart-contracts/quickstart
Git: https://github.com/near/docs/blob/00467b407b19bf1f6508268c27c6b3923f8b1b64/docs/2.build/2.smart-contracts/quickstart.md

Here's what I mean:

- <details>
	<summary> Starts with this, which is pretty decent </summary>

	> Notice the `cargo near`? Let's proceed
	
	<img width="50%" src="https://github.com/near/docs/assets/16881812/0ae0bf23-5999-4e51-b0dd-a3bb3739a7be">
	
	</details>

- <details>
	<summary>Rapidly devolves to this in the next section</summary>
	
	<img width="50%" src="https://github.com/near/docs/assets/16881812/200267af-685e-49e2-b4e5-5471731c1915">
	
	</details>

- <details>
	<summary>Wrong instructions to build the contract</summary>
	
	> `cargo build` will build a dynamic library for the target architecture, as opposed to the intended `wasm`
	>
	> I believe this was meant to be `cargo near build`?
	
	<img width="50%" src="https://github.com/near/docs/assets/16881812/682fa947-43e1-4f44-a41a-890ec1446950">
	
	</details>

- <details>
	<summary>And now we're on the verbose syntax</summary>
	
	> yes, `cargo CMD` == `cargo-CMD CMD`
	> 
	> but now using the alternative verbose syntax is unnecessary and confusing
	
	<img width="50%" src="https://github.com/near/docs/assets/16881812/97665bc6-de47-4064-ab92-f764bd4eec2a">
	
	</details>

- <details>
	<summary>And now we're done with the pretty tabs</summary>
	
	<img width="50%" src="https://github.com/near/docs/assets/16881812/aa78cd0d-cf4d-4ee2-8cda-455c6be5d2db">
	
	</details>

**Comment by flmel** [comment]
Thanks for flagging. There is a current work into consolidating some docs and revamping the section you are refferring to and almost all this are already addressed. Will update here when PR is merged.
