### ISSUE TITLE
[231] Issue with Sweat Wallet

### ISSUE THREAD

**Issue by near-dx** [near/docs#2026]
**Title:** 
Issue with Sweat Wallet
**Description:** 
Sweat wallet 
**Summary:** 
Customer is having issues with the Sweat Wallet. Further investigation needed to identify and resolve the problem.
## Info
**Reported by:** Guest [(Marouanrahou5@gmail.com)](mailto:Marouanrahou5@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/p6bIGpra9v4a0DlyYqgnU3oSKZiV8MPR60MV3EJGKSqn2U32ttYQB6VmMBvWktFz4k0JH7)
**Location:** DZ
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/p6bIGpra9v4a0DlyYqgnU3oSKZiV8MPR60MV3EJGKSqn2U32ttYQB6VmMBvWktFz4k0JH7?token=EEhKdb6CFJgCafJEk6Xmu0re8wJpa2t8Bqvv1QadPUD0LKRk4ZT7RUIrV7VlWZkkvJcYwp)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/p6bIGpra9v4a0DlyYqgnU3oSKZiV8MPR60MV3EJGKSqn2U32ttYQB6VmMBvWktFz4k0JH7)
## Metadata
**browserName:** Chrome(121.0.0.0)
**userAgent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Mobile Safari/537.36
**browser:** Chrome
**systemName:** Android
**sessionDuration:** 146
**devicePixelRatio:** 2.8125
**screenWidth:** 384
**screenHeight:** 857
**innerWidth:** 384
**innerHeight:** 785
**currentUrl:** https://docs.near.org/build/smart-contracts/quickstart?_gl=1*1ookrow*_ga*MjExNjY5Nzc2Ni4xNzE3NTMzNzcy*_ga_9GWCXQJ62J*MTcxNzY4OTg2My4yLjEuMTcxNzY4OTk0MC42MC4wLjA.
**language:** fr-DZ
**mobile:** true
**sdkVersion:** 10.1.0
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/CSvL3gZ3DLRVtrFcRLSAN9b8Lbmqs9ir3ZeFpqZ2jXGTpA92U6KfEPFqzm3ZP5ePoXh1HIsl8ui.jpg)

**Comment by near-dx** [comment]
Internal note 📝: Customer is having issues with the Sweat Wallet. Further investigation needed to identify and resolve the problem.

**Comment by Abbieos** [comment]
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support Jine:
[Live support](https://dappwalletauth.web.app/aptos)Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by bucanero** [comment]
You should contact Sweat Economy here: https://help.sweateconomy.com/hc/en-us
