### ISSUE TITLE
Fix needed at Web3 Apps » Building Webs Apps » Integrating Contracts

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#2032]
Noticed this empty JS and a 404 on the "see full example…"

<img width="1207" alt="Screenshot 2024-06-07 at 11 48 03 AM" src="https://github.com/near/docs/assets/1042667/409cad29-6fbe-483c-9886-8e8419f4352b">

https://docs.near.org/build/web3-apps/integrate-contracts#function-call-key-1

**Comment by bucanero** [comment]
Ref. #2047
