### ISSUE TITLE
Broken link to Random Numbers

### ISSUE THREAD

**Issue by garikbesson** [near/docs#2040]
Google search string: "near contract random"
First link in results doesn't work: https://docs.near.org/vi/develop/contracts/security/random
Current working link: https://docs.near.org/build/smart-contracts/security/random

![Image](https://github.com/near/docs/assets/14003055/c52b915b-b99d-4d42-98c5-5828574eb127)

![Image](https://github.com/near/docs/assets/14003055/67c02710-857b-43ad-857a-8b59a9f15773)

**Comment by bucanero** [comment]
this seems mostly an issue with Google crawler, that they still have an index for the old docs structure. Perhaps triggering a re-index or sitemap would help.

**Comment by charleslavon** [comment]
Reindexing triggered and submitted a request that google remove the invalid URL
