### ISSUE TITLE
[BUG] Missing JS snippets for integrate contracts

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#2047]
[Integrate contracts article](https://docs.near.org/build/web3-apps/integrate-contracts) has missing JS examples: 
<img width="598" alt="Screenshot 2024-06-10 at 7 17 04 PM" src="https://github.com/near/docs/assets/58483342/ee0b8091-6adb-450c-a8ef-5b91940343d1">
<img width="594" alt="Screenshot 2024-06-10 at 7 16 57 PM" src="https://github.com/near/docs/assets/58483342/97f5195c-6991-4842-b006-9b5352f8dfed">
<img width="636" alt="Screenshot 2024-06-10 at 7 16 48 PM" src="https://github.com/near/docs/assets/58483342/573260cc-a1c4-45c2-8d37-9b16dfe42ce4">

**Comment by thisisjoshford** [comment]
Hey @victorchimakanu, are you still working on this issue?

**Comment by VictorBagel** [comment]
@thisisjoshford Im not , Guillermo reassigned it to Lyudmil

**Comment by victorchimakanu** [comment]
@thisisjoshford I'm not, guillermo reassigned it to Lyudmil

**Comment by thisisjoshford** [comment]
> @flmel can you check this out with @victorchimakanu ? looks like the snippets are still broken

@flmel lmk if you can prioritize this as we have a new article on how to create frontends that relies on this and currently broken.
