### ISSUE TITLE
[DOC] Fix broken links 

### ISSUE THREAD

**Issue by PiVortex** [near/docs#2092]
There are some entry points to the docs from browser that need to be fixed. Please add anymore you find.
List of broken links:

- [x] https://docs.near.org/sdk/welcome
- [x] https://docs.near.org/sdk/js/testing/integration-tests
- [x] https://docs.near.org/sdk/rust/testing/integration-tests#:~:text=Integration%20tests%20provide%20the%20ability,structured%20execution%20outcomes%2C%20and%20more.
- [x] https://docs.near.org/sdk/rust/testing/unit-tests

**Comment by gagdiez** [comment]
fixed by adding redirects on Render
