### ISSUE TITLE
[BUG] Argument of Type Uint8 Array is not assignable to parameter of type PublicKey

### ISSUE THREAD

**Issue by s-n-park** [near/docs#2102]
**Describe the bug** 🐞
User reported bug: "Argument of Type Uint8 Array is not assignable to parameter of type **PublicKey**" for the page [SDK JS Promises create account](https://docs.near.org/sdk/js/promises/create-account)
([feelback](https://panel.feelback.dev/projects/03925b69-72cd-4bc8-b26e-bcf88f89e542/feelbacks/e538a8ae-5191-48c4-a341-9aaac5ab61a9))

**Expected behavior**

**Screenshots**

**Location** 🎯
Please link to the page that you see this issue.

**Comment by bucanero** [comment]
Note: we recently moved away from `/sdk/***` documentation and merged+migrated everything to a single learning path for building smart contracts.

We need to confirm this reference to Uint8 still exists (might have been removed already)

**Comment by bucanero** [comment]
This was fixed in https://github.com/near/docs/pull/2087
