### ISSUE TITLE
[249] Inquiry about near-docs.io ownership

### ISSUE THREAD

**Issue by near-dx** [near/docs#2121]
**Title:** 
Inquiry about near-docs.io ownership
**Description:** 
Hi, is near-docs.io maintain by near.org?
**Summary:** 
Customer is seeking clarification on the relationship between near-docs.io and near.org.
## Info
**Reported by:** Guest [(aondaop@gmail.com)](mailto:aondaop@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/xA1UHNnFl0paPveIkav5BNdU4RPdeCLAwsa5GChnCYtGx6ssQdhYffMXWrqk4HSI0sqP7h)
**Location:** ID
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/xA1UHNnFl0paPveIkav5BNdU4RPdeCLAwsa5GChnCYtGx6ssQdhYffMXWrqk4HSI0sqP7h?token=C2PUvLL4Jk9bUyHm50QJkGxrWEvi8l3Vy5ecXZxzAWA1BDY6jd69EOiOnbqDhfpioFE5zn)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/xA1UHNnFl0paPveIkav5BNdU4RPdeCLAwsa5GChnCYtGx6ssQdhYffMXWrqk4HSI0sqP7h)
## Metadata
**browserName:** Safari(17.4.1)
**userAgent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1
**browser:** Safari
**systemName:** iPhone
**sessionDuration:** 51
**devicePixelRatio:** 2
**screenWidth:** 414
**screenHeight:** 896
**innerWidth:** 414
**innerHeight:** 723
**currentUrl:** https://docs.near.org/build/smart-contracts/security/bounty
**language:** id-ID
**mobile:** true
**sdkVersion:** 13.7.3
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/MTSujCcvAkhari6gqcB634aJcYO0aLaG52gP0tPvQTjMSvaYxWbdwbTngiQ2KJ166KQg11CyLu8.jpg)

**Comment by near-dx** [comment]
Internal note 📝: Customer is seeking clarification on the relationship between near-docs.io and near.org.

**Comment by bucanero** [comment]
Yes, `near-docs.io` is just an alias URL of `docs.near.org`. We still suggest keeping docs.near.org as your bookmark address.
