### ISSUE TITLE
🔹[EPIC] Update wallet docstring

### ISSUE THREAD

**Issue by PiVortex** [near/docs#2125]
### Description

The docstring for getTransactionResult in near.js featured in frontend examples is incorrect.

---

### Goal

Change every description to "Retrieves transaction result from the network"

---

### Resources

PRs made:
- https://github.com/near-examples/near-multichain/pull/26
- https://github.com/near-examples/hello-near-examples/pull/15
- https://github.com/near-examples/guest-book-examples/pull/14
- https://github.com/near-examples/donation-examples/pull/13
- https://github.com/near-examples/coin-flip-examples/pull/24
- https://github.com/near-examples/counters/pull/10

---

**Comment by gagdiez** [comment]
@race-of-sloths add this epic!
