### ISSUE TITLE
[DOC] Add documentation explaining staked vs locked balance mechanic

### ISSUE THREAD

**Issue by nearmax** [near/docs#214]
We need a documentation explaining how our staking works and what is the difference between staked vs locked balance.

**Comment by amgando** [comment]
assigning to @bowenwang1996 because input needed via sync

**Comment by jimmy3dita** [comment]
@amgando I'm working on the FAQ about staking which may be related with this.
I talked with @ilblackdragon , he's putting together an "economics specs" which provide the constants of the protocol - ready to be plugged into any spreadsheet or business plan.
My FAQ notes are on Notion, here: https://www.notion.so/nearprotocol/Staking-FAQ-Notebook-6d0ebce6d4424098917f6959b2c5788d

Any explicit questions have emerged during the calls with the counterpart? They might be a great addition for the FAQ anyway

**Comment by amgando** [comment]
@ilblackdragon can you provide guidance here?  
@jimmy3dita just shared this link: https://nomicon.io/Economics/README.html#state-stake
