### ISSUE TITLE
[DOC] Add link to dev.near.org/applications

### ISSUE THREAD

**Issue by s-n-park** [near/docs#2166]
**Is your feature request related to a problem? Please describe.**
User left feedback: I'm looking for a list of dapps. docs.near.org doesn't give me any idea what kind of dapps are running on the network or how to find them.
[Feelback](https://panel.feelback.dev/projects/03925b69-72cd-4bc8-b26e-bcf88f89e542/feelbacks/9d88169c-79d8-45b8-aedc-5f9941e92b6f)

Left for this page: https://docs.near.org/build/primitives/dao/near-cli/get-proposal-list

**Describe the solution you'd like**
We should add some sort of link within documentation to help users find what they are looking for.

**Additional context**

**Comment by s-n-park** [comment]
2 PRs:
- Added screenshot: https://github.com/near/docs/pull/2168
- Added to Docs: https://github.com/near/docs/pull/2169

**Comment by s-n-park** [comment]
@bucanero - would it be possible to get quick review on these 2, very quick/easy changes I made quickly :)

**Comment by bucanero** [comment]
reviewed and merged 👍  thanks @s-n-park ! 🙏
