### ISSUE TITLE
[258] Token farm functionality issue

### ISSUE THREAD

**Issue by near-dx** [near/docs#2223]
**Title:** 
Token farm functionality issue
**Description:** 
Token farm no longer works 
**Summary:** 
The customer is experiencing an issue with the token farm feature, which is no longer functioning. This appears to be a critical issue and should be addressed promptly to avoid further dissatisfaction.
## Info
**Reported by:** Guest [(ska7eordie@gmail.com)](mailto:ska7eordie@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/2yR21D67SqNhae6sUC2vFGu7g3pmqqt1l7YZRk3tGslTFhgwOtqBffnvtruwbDWeC7ud7N)
**Location:** US
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/2yR21D67SqNhae6sUC2vFGu7g3pmqqt1l7YZRk3tGslTFhgwOtqBffnvtruwbDWeC7ud7N?token=DYOuhTpNpC6Y7zGscMhQKfRniWHgavLJR1K1r5at0noQniwCDY0eB0tDRB5OO9DVgIhfaq)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/2yR21D67SqNhae6sUC2vFGu7g3pmqqt1l7YZRk3tGslTFhgwOtqBffnvtruwbDWeC7ud7N)
## Metadata
**browserName:** Safari(17.5)
**userAgent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
**browser:** Safari
**systemName:** iPhone
**sessionDuration:** 481
**devicePixelRatio:** 3
**screenWidth:** 393
**screenHeight:** 852
**innerWidth:** 393
**innerHeight:** 741
**currentUrl:** https://docs.near.org/build/primitives/ft
**language:** en-US
**mobile:** true
**sdkVersion:** 13.7.3
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/YMGE8u0UBkd0Hh8VcWtbeNMpntPYs8kiQtKpk7C6R3xi7zU0XsVVPSvTUUDNCrrOAIFUBhm4hnb.jpg)

**Comment by near-dx** [comment]
Internal note 📝: The customer is experiencing an issue with the token farm feature, which is no longer functioning. This appears to be a critical issue and should be addressed promptly to avoid further dissatisfaction.

**Comment by gagdiez** [comment]
@flmel lets redirect people to dev.near.org

**Comment by flmel** [comment]
> @flmel lets redirect people to dev.near.org
Let's make sure we have the testnet support before that.

**Comment by gagdiez** [comment]
@flmel token farm never had a mainnet that I knew. Anyways, we have added the testnet.

Please let me know if you can fix it, otherwise please ask @garikbesson for the help while I'm out
