### ISSUE TITLE
[META] how our issue / PR management process works

### ISSUE THREAD

**Issue by amgando** [near/docs#223]
@nearmax does it make sense to document this publicly (ie. docs.nearprotocol.com contributor guidelines or better, right here on GitHub)?

![image](https://user-images.githubusercontent.com/24913/74584746-9a6b0a00-4fe6-11ea-86a1-183c66c073c7.png)
![image](https://user-images.githubusercontent.com/24913/74584750-abb41680-4fe6-11ea-87c6-6717538940f6.png)

**Comment by gagdiez** [comment]
This has not been implemented, but a new issue should be opened if still relevant @thisisjoshford .
