### ISSUE TITLE
[BUG] Update Zero to Hero

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#224]
Sorry, in the throes of the hackathon, quickly recording that zero to hero needs some updates:
https://docs.nearprotocol.com/docs/tutorials/zero-to-hero#cleaning-up-the-front-end

Here's a link to something it seems to reference:
https://github.com/nearprotocol/NEARStudio/blob/c0935b0ffd87fc3ce70b3218ef8fba73071457f4/templates/01-hello-username/src/index.html

**Comment by amgando** [comment]
this is the challenge with docs that discuss code samples :)

here's the change that took this out of sync
https://github.com/nearprotocol/NEARStudio/commit/d26267230fe8a32eaf2c76419a9a8dc027bb6975#diff-cdeda820238e786c5dce831aad2efde9

**Comment by mikedotexe** [comment]
I'm not attached to the old Zero to Hero. I see that we've removed it from the sidebar. Since so much has changed in NEAR, I vote that we don't try to "update" this doc and instead write a new one, perhaps using an actual oracle when that becomes ready.

**Comment by amgando** [comment]
@mikedotexe sounds awesome, please take it on
