### ISSUE TITLE
[267] Function Call Key Code Example Missing

### ISSUE THREAD

**Issue by near-dx** [near/docs#2267]
**Title:** 
Function Call Key Code Example Missing
**Description:** 
Function call key code example is empty
**Summary:** 
The customer has reported that a function call key code example is missing. Please verify the documentation or code samples to ensure completeness and provide the necessary example to the customer. Ensure to follow up with the customer to confirm resolution.
## Info
**Reported by:** Guest [(cuongdcdev@gmail.com)](mailto:cuongdcdev@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/sjkhL2GKZKomH8ECUoRt9NIRXTVMiX5b3NBeKnjBzHPZsaDlscrhxg9GjxW0RWWr81CePi)
**Location:** HK
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/sjkhL2GKZKomH8ECUoRt9NIRXTVMiX5b3NBeKnjBzHPZsaDlscrhxg9GjxW0RWWr81CePi?token=sTIQ96UMxpF4zuLyHGwug3v9MCsl9eVIzVEW7s1QunIZ1B0zefgpohbfQIxyyEQ95y3Tjq)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/sjkhL2GKZKomH8ECUoRt9NIRXTVMiX5b3NBeKnjBzHPZsaDlscrhxg9GjxW0RWWr81CePi)
## Metadata
**browserName:** Chrome(130.0.0.0)
**userAgent:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
**browser:** Chrome
**systemName:** Linux
**sessionDuration:** 8246
**devicePixelRatio:** 1
**screenWidth:** 1920
**screenHeight:** 1200
**innerWidth:** 1920
**innerHeight:** 1083
**currentUrl:** https://docs.near.org/build/web3-apps/integrate-contracts
**language:** en-US
**sdkVersion:** 13.7.3
**sdkType:** javascript
**environment:** prod

![Screenshot](https://staticfiles.gleap.io/p6272ba4eb62acc0036624b99/1G9vaVnOSm7GKd1azmufyig4r8a9c3Bo1YDgoZo6GD92xMLTvjJfIpNCXW1PZrFxPI4ygb3iZ9t.jpg)

**Comment by near-dx** [comment]
Internal note 📝: The customer has reported that a function call key code example is missing. Please verify the documentation or code samples to ensure completeness and provide the necessary example to the customer. Ensure to follow up with the customer to confirm resolution.

**Comment by PiVortex** [comment]
Fixed by #2266
