### ISSUE TITLE
[DOC] Tutorial for storing simple key/value

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#227]
**Is your feature request related to a problem? Please describe.**
There should be an easy example how to store from key/values from the nearlib.

**Describe the solution you'd like**
Existing contract already deployed that can store key/values.
And 3-4 line in JS to how to use this from client.

**Additional context**
Ideally should be similar to firebase's example and provide a quick on ramp for developers to have "first app using crypto".

**Comment by chadoh** [comment]
> should be similar to firebase's example

What example, @ilblackdragon?
