### ISSUE TITLE
[270] Inquiry about Wallet Selector Support for Cocos Creator

### ISSUE THREAD

**Issue by near-dx** [near/docs#2273]
**Title:** 
Inquiry about Wallet Selector Support for Cocos Creator
**Description:** 
How to make Wallet Selector support cocos creator 2. X three. X?
**Summary:** 
The customer is seeking information on how to integrate or utilize Wallet Selector with Cocos Creator versions 2.X and 3.X. Provide guidance on compatibility or integration steps.
## Info
**Reported by:** Guest [(necklace1982@gmail.com)](mailto:necklace1982@gmail.com) - [Open in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/NjjUYjH14YPlSqXpuAHlVDvLLgl6vGsXzNgenpjJUmFI72v5YQ255SXyE3ucJwnz2f29Ab)
**Location:** JP
**Type:** 🚨 BUG

🔗 [Open share link](https://app.gleap.io/share/NjjUYjH14YPlSqXpuAHlVDvLLgl6vGsXzNgenpjJUmFI72v5YQ255SXyE3ucJwnz2f29Ab?token=yC3rw79ZfkBqhIQLdvcSosTCp3s0Z8Wp1k3f4IzgdQumm8Pj7gXwXdmEcWX8F2BfCAHIf5)
🌍 [Open ticket in Gleap](https://app.gleap.io/projects/6272ba4eb62acc0036624b99/bugs/NjjUYjH14YPlSqXpuAHlVDvLLgl6vGsXzNgenpjJUmFI72v5YQ255SXyE3ucJwnz2f29Ab)
## Metadata
**browserName:** Safari(17.6)
**userAgent:** Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1
**browser:** Safari
**systemName:** iPhone
**sessionDuration:** 118
**devicePixelRatio:** 3
**screenWidth:** 428
**screenHeight:** 926
**innerWidth:** 428
**innerHeight:** 745
**currentUrl:** https://docs.near.org/tools/ethereum-wallets
**language:** zh-CN
**mobile:** true
**sdkVersion:** 13.7.3
**sdkType:** javascript
**environment:** prod

![Screenshot]([object Object])

**Comment by near-dx** [comment]
Internal note 📝: The customer is seeking information on how to integrate or utilize Wallet Selector with Cocos Creator versions 2.X and 3.X. Provide guidance on compatibility or integration steps.

**Comment by PiVortex** [comment]
This is a question from the telegram group, it does not seem like a relevant issue

**Comment by flmel** [comment]
Highly specific to the game engine in question https://www.cocos.com/en/creator some of the their examples have relevant clues https://docs.cocos.com/creator/3.8/manual/en/cases-and-tutorials/
