### ISSUE TITLE
[DOC] Ethereum bridge needs documentation and sample code

### ISSUE THREAD

**Issue by amgando** [near/docs#232]
developer section is the most likely location for this work: 
https://docs.nearprotocol.com/docs/roles/developer/quickstart

- [ ] add note on quickstart page titled `NEAR and Ethereum` linking to deeper pages
- [ ] add a section to include multiple pages for this topic (ie. intro, bridge, evm)
- [ ] create an intro page with some context
- [ ] create a page for the Ethereum bridge
- [ ] create a page for EVM

**Comment by amgando** [comment]
@k06a can you provide links to existing content that would help document this work please?

**Comment by thisisjoshford** [comment]
Closing this issue as https://github.com/near/docs/issues/642 is a more recent tracking for this. Also #234 has been closed (EVM Documentation)
