### ISSUE TITLE
[DOC] Document usage of  EVM 

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#234]
Currently documentation are examples in the https://nearprotocol.com/blog/running-ethereum-applications-on-near/ - we should have it here as well and link in the blog to the documentation.

**Comment by amgando** [comment]
#232 duplicate

**Comment by ilblackdragon** [comment]
@amgando Nope, that issue is about bridge and this one is about EVM - https://github.com/nearprotocol/near-evm & https://github.com/nearprotocol/near-web3-provider

**Comment by amgando** [comment]
my bad, deleted

**Comment by thisisjoshford** [comment]
https://github.com/near/docs/pull/649 Fixes this
