### ISSUE TITLE
[DOC] add samples for near-openweb-js

### ISSUE THREAD

**Issue by amgando** [near/docs#236]
open web library was recently published
https://github.com/nearprotocol/near-openweb-js

would be good to have several examples of using this in the docs.

http://metanear.com is low hanging fruit as an example or to convert to a starter kit that can be cloned

source code
https://github.com/nearprotocol/near-open-web-frontend
https://github.com/nearprotocol/near-bindgen/pull/66/files

**Comment by amgando** [comment]
now moved to it's own org: https://github.com/metanear

**Comment by thisisjoshford** [comment]
closing this issue as `metanear` seems to be an abandoned project. Feel free to re-open issue if this is not the case @amgando
