### ISSUE TITLE
[DOC] need comprehensive guide on Rust contracts compiled to Wasm

### ISSUE THREAD

**Issue by amgando** [near/docs#239]
we need a comprehensive guide on rust contracts that would explain all nitty gritty details on what happens with Wasm compilation

related notes from recent thread between @nearmax and @mikedotexe 

- try running it on the node and check that everything works correctly, including cross-contract calls. [run through steps in here](https://github.com/nearprotocol/near-bindgen/tree/master/examples/cross-contract-high-level) and verify that it works correctly. make sure you remove old wasm file and target directory before compiling.
- make sure you are using stable Rust in case they are experimenting with Wasm in nightly.
- Wasm files are libraries and that specific lib annotation is designed to make it work correctly,
- walk through https://rustwasm.github.io/book/ to get a better understanding what is the difference between Rust compiled to Wasm and Rust contract compiled to Wasm.
-  unit tests perform a non-trivial fixture needed for the contract to function.
- when unit tests are compiled they are compiled for non-wasm platform and their code is slightly different (does not contain JSON/Borsh wrappers).

**Comment by nearmax** [comment]
@amgando thank you so much for taking care for scoping it and creating an issue!

In addition to https://github.com/nearprotocol/near-bindgen/tree/master/examples/cross-contract-high-level here is piece of documentation that I send to people: https://github.com/nearprotocol/workshop

**Comment by gagdiez** [comment]
This looks like too deep for our documentation. Maybe for nomicon.io? We could add a link in our docs to https://rustwasm.github.io/book/ ?
