### ISSUE TITLE
[DOC] address recent telegram chat output

### ISSUE THREAD

**Issue by amgando** [near/docs#251]
**Jasper de Gooijer**
Does anybody have experience with bugs that cause issues (I think it's an overflow bug) on TestNet but work fine in unit tests? 

Feel like there's some overflow bug that's only caused on TestNet but it's hard to debug.

**Maksym Zavershynskyi**
Unless you are using cross-contract calls, it is probably serialization. 

Check the following:
* The account state is compatible, i.e. a contract was not deployed over a state that was used by a different code.  To check if this is the issue, remove the account entirely and re-create it.  If it works, this was the issue.
* It might be a problem of passing arguments in JSON format. Make sure you are not using `u128`, because handling of `u128` diverges for Rust and JS libraries. To check, comment out the body of the contract method and just call it with the same args.  If it still fails then the problem is in serialization, if it doesn't fail then the problem is with the body of the contract method.

**Jasper de Gooijer**
I am using `u128` and i did redeploy after deleting :) 

might be the `u128` issue

If i pass in < 1e12 the method executes correctly, else it overflows somewhere during execution.

But it always works while unit testing

Maybe I'll decrease denomination overall to support `u64`?

The Tx never fails btw, it just executes differently, pretty sure it isn't serialization even though this also was my first guess.

**Maksym Zavershynsky**
That's weird, JSON is supposed to work fine with less than 53 bits, and 1e12 is under that. If you can point to the code then I can take a look.

Is it possible that you are running tests in debug mode? Rust handles overflows differently in debug and release modes: https://huonw.github.io/blog/2016/04/myths-and-legends-about-integer-overflow-in-rust/

**Jasper de Gooijer**
yes that is possible

Yea so JS is not the issue :)

The debug = false flag in cargo.toml handles this I assume?

This is the initial method that's being called: 
https://github.com/jasperdg/flux-protocol/blob/master/src/markets.rs#L87

But I suspect the issue to occur somewhere around here:
https://github.com/jasperdg/flux-protocol/blob/master/src/markets/market.rs#L59

**Maksym Zavershynskyi**
> _The debug = false flag in cargo.toml handles this I assume?_

No, the flag states that in the compilation mode called "release" the debug instructions should not be included.

Basically, it depends on how exactly you run your tests, i.e. what IDE or what cargo command. If you explicitly see an overflow panic when you run a test then it is almost certainly because you are running it in the debug mode. (Unless you are explicitly using checked arithmetic operations, like https://doc.rust-lang.org/std/primitive.u64.html#method.checked_add which does not seem to be the case)

So it probably overflows without panic when executed as a Wasm contract (because we compile Wasm contract in the release mode) and just wraps.

**Jasper de Gooijer**
Interesting.

**Maksym Zavershynskyi**
It’s a DevX issue, we should find a Cargo.toml command to make it always panic, add it to our examples to force consistent panic, add mention in the documentation. Sorry, for the inconvenience.

**Jasper de Gooijer**
> So it probably overflows without panic when executed as a Wasm contract

Yep that makes sense, the only annoying thing is that with the exact same test scenario running unit tests the code does perform as expected.

So it's super hard to debug

When the bug is only on a deployed contract

**Maksym Zavershynskyi**
Yes, we should enforce more consistency ourselves to workaround the inconsistency on Rust side.

Rust does it for performance reasons.

**Jasper de Gooijer**
Yep I read that. I'm just contemplating how to tackle this problem now.

btw regarding the `u128` divergency issue between Rust and JS, that could be fixed by serializing all integers to `BN.js` objects right?

**Maksym Zavershynskyi**
Hopefully, there is a Cargo.toml config option that we can turn on to make Wasm panic on overflows. I am investigating now..

>btw regarding the `u128` divergency issue between Rust and JS, that could be fixed by serializing all integers to `BN.js` objects right?

Yes, but then on the Rust side you have to treat them as strings..

**Jasper de Gooijer**
That would be awesome

> Yes, but then on the Rust side you have to treat them as strings.

Oh damn.

**Maksym Zavershynskyi**
Because JSON just cannot handle large numbers...

Evgeny, is it correct that `BN.js` is a string on the Rust side?

**Evgeny Kuzyakov**
yes, it should be like this.

**Maksym Zavershynskyi**
Here is the solution to the overflow problem: https://stackoverflow.com/questions/34054669/how-to-compile-and-run-an-optimized-rust-program-with-overflow-checking-enabled

Just add overflow-checks = true under [profile.release] section.

**Evgeny Kuzyakov**
Wasm doesn't have automatic overflow checks, so you have to wrap all math into checked

**Maksym Zavershynskyi**
Or use the cargo toml config feature that I pasted above to always panic on overflows.

**Jasper de Gooijer**
This could be done at smart contract level?

**Evgeny Kuzyakov**
> Or use the cargo toml config feature that I pasted above to always panic on overflows.

I think this only works for Rust x86, but not for the wasm32 target. Need to check.

**Maksym Zavershynsky**
Mike, Chad, Sherif Important detail that you should be aware of ^

**Mike Purvis**
okay, thank you

**Evgeny Kuzyakov**
I checked wasm32 target and the overflow panics with   Just add overflow-checks = true under [profile.release] section.

**Maksym Zavershynskyi**
Awesome, thanks Evgeny. Now we just need to add this line to all our examples and mention in the documentation.

**Comment by amgando** [comment]
@mikedotexe i think there are a few specific takeaways for us here: 

1. update examples to include compiler checks on by default

   ```
   Just add overflow-checks = true under [profile.release] section.
   ```

2. can't use large sizes with Wasm (ie. `u128`) -- max is `u64`

3. Two troubleshooting steps for contract development

   ```
   - The account state is compatible
   - It might be a problem of passing arguments in JSON format. 
   ```

am i missing anything?

**Comment by thisisjoshford** [comment]
Cleaning up issues and closing this one as its over a year old and may no longer be valid.
