### ISSUE TITLE
[DOC] add note about rust smart contract overflow

### ISSUE THREAD

**Issue by amgando** [near/docs#255]
from someone developing on the platform:

> Adding `overflow-checks = true` in cargo.toml makes your smart contracts after deployments behave more like the unit tests. So basically if there is large inconcistency between unit test execution and contract execution try this flag. > Probably good suggestion to always have this flag being true :)

**Comment by nearmax** [comment]
s/behave more like the unit tests/behave like the unit tests

**Comment by nearmax** [comment]
We also need to explain that the reason it is needed is because Rust handles overflows differently in release and debug modes. Specifically, it panics in debug and wraps in release. We might link this article https://huonw.github.io/blog/2016/04/myths-and-legends-about-integer-overflow-in-rust/

**Comment by gagdiez** [comment]
+1 on this, we created an internal ticket to update all the Developer examples.
