### ISSUE TITLE
[DOC] Validators landing page with basic economics info

### ISSUE THREAD

**Issue by jimmy3dita** [near/docs#260]
**Is your feature request related to a problem? Please describe.**
Our users should take a few seconds to understand how many tokens are needed to become a validator - so they can run their own math

**Describe the solution you'd like**
@jimmy3dita is going to add a new branch and work on its contents, such that a 5-seconds-UX-test with a validator will be successful
@amgando to review the structure and the language

**Additional context**
I have videos form UX interviews, can forward them separately to preserve privacy

**Comment by jimmy3dita** [comment]
@amgando I think we can close this, it's already there

**Comment by amgando** [comment]
closing
