### ISSUE TITLE
[SPEC] produce spec for NEAR

### ISSUE THREAD

**Issue by amgando** [near/docs#263]
**produce a spec at this level of detail**
https://github.com/nearprotocol/NEPs/blob/5710a4fce95ce3c53316b60607214425b52a3263/specs/Economics/README.md#state-storage-rent

**see here for discussion**
https://commonwealth.im/near/proposal/discussion/375-what-pseudocode-should-we-use-in-our-spec

**especially**
> _Python is a good choice, it is easy to understand, and most of the engineers can read Python. Interestingly, they also provide `SSZ equivalent` in some places. SSZ is their own serialization format, equivalent of Borsh. Since Borsh was written after Rust types, we can provide `Rust equivalent` in few places._

**see here for Economics wip**
https://github.com/nearprotocol/NEPs/blob/5710a4fce95ce3c53316b60607214425b52a3263/specs/Economics/README.md#state-storage-rent

**Comment by gagdiez** [comment]
We think that assemblyscript covers this need, and the new documentation is written in the following way:

- a textual explanation of concepts
- the smallest example in all SDKs, prioritizing assemblyscript.
