### ISSUE TITLE
[BUG] The "Life of a Transaction" scheme is not correct

### ISSUE THREAD

**Issue by fckt** [near/docs#268]
**Describe the bug**
The "Life of a Transaction" scheme is not correct.

**Expected behavior**
Transaction creates only 1  ActionReceipt. The `signer_id` in transaction denotes an account_id which is requested to create an ActionReceipt towards the `receiver_id`. So the Transaction is routed to the `signer_id` account first. This account will create (and charged for it) an ActionReceipt towards the `receiver_id`.

**Screenshots**
<img width="584" alt="Screen Shot 2020-03-17 at 17 34 04" src="https://user-images.githubusercontent.com/547167/76866666-816ba800-6875-11ea-814a-3255deffc9ce.png">

<img width="697" alt="Screen Shot 2020-03-17 at 17 37 34" src="https://user-images.githubusercontent.com/547167/76867023-0060e080-6876-11ea-8f97-a8be09319653.png">

Gives the wrong intuition that the Transaction application can create multiple Receipts by itself (only FuctionCall Receipt () application can lead to create multiple Receipts today).

**:pencil: Location**
https://docs.nearprotocol.com/docs/concepts/transaction#life-of-a-transaction

**Comment by amgando** [comment]
fixed in #378 but not closing automatically, not sure why
