### ISSUE TITLE
instructions for installing near-shell on windows can be simplified for happy case

### ISSUE THREAD

**Issue by janedegtiareva** [near/docs#280]
I did not follow the extra steps to resolve permissions instructions and just ran a npm install -g near-shell on a relatively clean windows. I think we can recommend that people try that, and move the other instructions to some sort of "common problems troubleshooting" section.

**Comment by janedegtiareva** [comment]
Also let's reorganize the content so that it's tabbed by OS (similar to how we do assemblyscript vs rust in other places)

**Comment by mikedotexe** [comment]
Link?

**Comment by mikedotexe** [comment]
Okay, I think you're talking about this link:

Did you use Windows Subsystem for Linux? Those instructions are specific to that.

If you didn't use WSL that's great news. I think we should wait to remove it from the docs until we have `create-near-app` working on [Windows through this PR](https://github.com/nearprotocol/create-near-app/pull/138). That won't run at all on Windows, but will run on WSL. As `create-near-app` is our primary entry point to getting started with NEAR, I'd rather tell every Windows user to use WSL, as it does in the docs for shell. Would have been great to have it in the `create-near-app` instructions, but let's get that working on Windows.

Phew, that was a lot of words. TL;DR: let's keep it until we merge the PR mentioned, then pull that whole section talking about Windows and WSL.

**Comment by ashleynear** [comment]
Notes for future self:

- test the experience on our [docs.near.org](https://docs.near.org/docs/development/near-shell) for windows
- update the steps for windows for any discrepancies

**Comment by thisisjoshford** [comment]
PR #155 fixes this :)
