### ISSUE TITLE
[DOC] Life of a contract

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#293]
**Is your feature request related to a problem? Please describe.**
Smart contracts are an alien term for most developers.
Specifically, properties around immutability, trust and others should be clearly communicate for people who are new to blockchain.

Additionally, there are various ways contracts can behave and live on MainNet.
For example here are set of options described - https://github.com/nearprotocol/NEPs/issues/40#issuecomment-602025607

**Describe the solution you'd like**
We should have a description that guides people:
 - mental model for smart contracts (and separately how NEAR can be used for serverless functions vs contracts)
 - various trust models, how to identify contracts that are trust-less, community ran or company/individual ran.
 - how the deployment will look like - specifically, key management, upgrades, financial questions

**Comment by doriancrutcher** [comment]
We now have this included in our documentation  here https://docs.near.org/docs/tutorials/contracts/nfts/upgrade-contract/#redeploying-contract
