### ISSUE TITLE
[DOC] Explain how to add additional gas to a transaction

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#299]
**Is your feature request related to a problem? Please describe.**
Yes, internally, @olonho noticed this error:
```bash
errors.js:17 Uncaught (in promise) Error: Transaction A9BzFKmgNNUmEx9Ue9ARC2rbWeiMnq6LpcXh53xPhSN6 failed. Exceeded the prepaid gas
```

Nikolay eventually solved this with help from @frol by using:
```js
const BN = require('bn.js');
...
const result = await window.contract.vote({poll_id: window.voteState.pollId, votes: votes},
        new BN(10000000000000));
```

**Describe the solution you'd like**
Provide clear instructions how to pass a value for gas when making a transaction call.

**Additional context**
We currently have a (rather crummy) example of this in the Guest Book:
https://github.com/near-examples/guest-book/blob/master/src/App.js#L31

If using `near-api-js` this eventually goes to:
https://github.com/near/near-api-js/blob/092d6477854906e51a59a406f0587b1174e4d02b/lib/contract.js#L30

**Other Notes**
Vlad mentioned we can query for how much gas is already used with:
https://github.com/near/near-sdk-as/blob/06901e38fa03fa3fffd8830f4be31899086935cf/assembly/runtime/contract.ts#L79
I don't have an example of this off the top of my head at the time of this writing. Other may feel free to comment/edit.

**Comment by vgrichina** [comment]
I think we also need to change it to support optional named args, so that calls with attached gas/amount look like:

```js
await contract.addMessage({ text }, { gas: BOATLOAD_OF_GAS,  amount: isPremium ? PREMIUM_COST.toString() : '0' })
```

or given that default gas is enough just:

```js
await contract.addMessage({ text }, { amount: isPremium ? PREMIUM_COST.toString() : '0' })
```

**Comment by vgrichina** [comment]
> Vlad mentioned we can query for how much gas is already used with

This is a bit orthogonal. Wasn't clear what's @olonho concern originally. However we also need to explain it in docs, specifically we need to cover how to code contracts which don't necessarily use deterministic account of gas (e.g. I think @nearmax had some map-reduce implementation).

I think what we can also do on near-api-js side is include helpful info for every message. 
See https://github.com/near/near-api-js/blob/e0181966003f9b0426b9a2e5c8bff3fcee7980ba/src/res/error_messages.json 

E.g. in this example "Exceeded the prepaid gas" we can include link to relevant example in docs (on how to attach gas) in error message.  

@mikedotexe basically I think it is pretty cool devx project to go over that error file and provide more useful error messages.

**Comment by amgando** [comment]
@chadoh this seems like it would be relevant to #368 as well

**Comment by thisisjoshford** [comment]
This is now explained here: https://docs.near.org/docs/faq/naj-faq#how-do-i-attach-gas--a-deposit
