### ISSUE TITLE
[FIX] Update running a node instructions

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#307]
This is more of a soon-to-be bug.

**Describe the bug**
Currently we have:
https://docs.nearprotocol.com/docs/local-setup/running-testnet

to explain how to set up a node. The python scripts are getting phased out.

We'll need to instruct users on how to use nearup.

**Other Notes**:
For folks not using Docker, possibly:
```
git clone https://github.com/nearprotocol/nearcore.git
cd nearcore
cargo build -p neard --release
```
Binary will be at `target/release/neard`

We'll have to make sure the user has git and Rust (cargo) installed.

Also, it's possible the command using `nearup` will be:
`nearup {environment}net --nodocker --binary-path path/to/nearcore/target/{debug, release}`

We'll have to update and test to make sure.

**Comment by navneetlakra** [comment]
I have created a pull request (https://github.com/near/docs/pull/384) for this. Please review.
