### ISSUE TITLE
[DOC] Provide list of security attack vectors and our response

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#308]
**Is your feature request related to a problem? Please describe.**
In discussions internally, we found this list to be quite well-made:
https://www.cosmwasm.com/docs/getting-started/smart-contracts#lessons-learned-from-ethereum

The goal is to provide a similar page and to work with Evgeny Kuz. and Max to go through the list and provide accurate responses.

**Comment by doriancrutcher** [comment]
In the new upcoming docs we have new page in the works for security https://near-docs.io/develop/contracts/security/storage
