### ISSUE TITLE
snippets: only replaces one instance in a file

### ISSUE THREAD

**Issue by janedegtiareva** [near/docs#309]
**Describe the bug**
Briefly describe the issue you're experiencing.

**Expected behavior**
Describe what you were expecting to find.

**Screenshots**

**:pencil: Location**
Please link to the page that you see this issue

**Comment by amgando** [comment]
@janedegtiareva can you fix the description here, i'm not sure what to do with this.  or is this just a note for yourself?

**Comment by amgando** [comment]
closing, let's just reopen if we pick this initiative back up
