### ISSUE TITLE
[DOC] Provide information about logging to end user

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#311]
**Is your feature request related to a problem? Please describe.**
There are cases where logging is useful to NEAR Collective folks as well as end users who are developing on NEAR. Currently it is not surfaced where logs can be found.

**Describe the solution you'd like**
Links and descriptions to these web sites:
http://grafana.neartest.com/d/main-testnet/main-testnet?orgId=1
http://prometheus.neartest.com/graph
https://rpc.nearprotocol.com/metrics

**Additional context**
I have no idea when and where exactly you use these, just that they exist and should be in the docs somewhere.

**Comment by doriancrutcher** [comment]
For more clarification do you mean where developers and users can look up transaction logs?
