### ISSUE TITLE
[DOC] AssemblyScript contract optimizations 

### ISSUE THREAD

**Issue by amgando** [near/docs#312]
**in AssemblyScript**

```ts
const compile = require('near-sdk-as/compiler').compile

compile('assembly/main.ts',   // input file
        'out/main.wasm',      // output file
        [
          //   "-O1",         // Optional arguments
          '--debug',
          '--measure',        // Shows compiler runtime
          '--validate'        // Validate the generated wasm module
        ], 
        {
          verbose: true       // Output the cli args passed to asc
        }
)
```

add all optimization options to this file so people know about them

for example, you can cut the contract size by half as well as reduce gas requirements significantly using this optional argument

`-O3z`

or we can pass these into the command line args directly

`yarn run build:contract —- -03z`

or we could update `package.json` scripts with these

```json
{ 
  "build:dev": "node asconfig.js", 
  "build:prod" : "node asconfig.js -O3z"
}

```

_note: none of the above is actually tested and so need careful review_

**Comment by willemneal** [comment]
see https://github.com/near/near-sdk-as/issues/43
