### ISSUE TITLE
[DOC] How to deploy to production (MainNet)

### ISSUE THREAD

**Issue by potatodepaulo** [near/docs#319]
We need a basic explainer page that shows the user how to change networks and deploy a finished application to main net.

**Comment by amgando** [comment]
@potatodepaulo can we shape this here?  what's in scope?  

is there more to it than this ...

- [x] starting with a working dApp on Localnet or Testnet
- [ ] run `export NEAR_ENV=mainnet` in the terminal
- [ ] create an account (using Mainnet Wallet or an existing local `master-account`)
- [ ] deploy the contract
