### ISSUE TITLE
[DOC] Explain common WASM errors

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#321]
**Is your feature request related to a problem? Please describe.**
Common WASM errors are not always clear, we should have a list of them with possible explanations.

**Describe the solution you'd like**
For example for:
```
Failure(ActionError(ActionError { index: Some(0), kind: FunctionCallError(HostError(MemoryAccessViolation)) }))
```

Possible explanaitions:
 - index out of bounds for memory access.
 - also happens when stuff does not fit into contract memory.
 - also happens when we are trying to fit stuff which is too large into the register. It can be thrown in many places so it would be helpful to know which line of code actually throws it.

**Comment by willemneal** [comment]
Another:
```
 { FunctionCallError: { WasmTrap: { msg: 'unknown' } } }
```
see: https://github.com/nearprotocol/nearcore/issues/2529

**Comment by amgando** [comment]
we have a list of errors but no accessible explanation that ties things back to the dApp developer perspective so this would be really helpful

https://docs.nearprotocol.com/docs/roles/integrator/errors/introduction
