### ISSUE TITLE
[DOC] Document important runtime constants

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#322]
**Is your feature request related to a problem? Please describe.**
There are plenty of runtime constants, like default amount of gas for view functions, max contract size, etc. We should have a list of them with explanations and SEOable.

For example we have a ton of constants here: https://github.com/nearprotocol/nearcore/blob/05a82d8dd74531b21567623ab0e7e75946afea19/runtime/near-vm-logic/src/config.rs#L124

**Comment by amgando** [comment]
we have this: https://docs.nearprotocol.com/docs/api/vm-limits

does that satisfy the request?

**Comment by amgando** [comment]
closing since it seems like this was done
