### ISSUE TITLE
[DOC] Validator contract migration and upgrade docs

### ISSUE THREAD

**Issue by htafolla** [near/docs#342]
When a new validator contracts becomes available there is not clear documentation on how to migrate an existing staked validator or existing contract to a new contract.

I would like to take the tasks of creating these docs:
1. Migrating a staked validator to a contract
2. Migrating an existing contract to a new one.

I will however need some guidance from the team on a few points:
1. Does near create_account always overwrite ~/.near/betanet/validator_key.json?
2. Should near-shell be upgraded first before migrating?
3. When upgrading a contract to you need to unstake and withdrawn before pushing the new one.

**Comment by bowenwang1996** [comment]
> Does near create_account always overwrite ~/.near/betanet/validator_key.json?

Never

> Should near-shell be upgraded first before migrating?

Not necessarily, but it also doesn't hurt to upgrade.

> When upgrading a contract to you need to unstake and withdrawn before pushing the new one.

Are you talking about contracts generally or some specific contract?

**Comment by htafolla** [comment]
@bowenwang1996 I've learned so much since then! 😄 

I actually forgot about this, but have addressed the first one in a PR.

As for the question, I was asking when you update an existing contract you have already deployed do you have to unstake your delegators first. I do not think you need to unstake them and now I know you can't they would have to.

**Comment by amgando** [comment]
@htafolla can we close this issue then?

**Comment by htafolla** [comment]
Sorry. Yes.
