### ISSUE TITLE
[DOC] Explain nonce-ordering and how they're handled after transaction is sent.

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#344]
**Is your feature request related to a problem? Please describe.**
One of our projects has found that nonces do not get executed sequentially as expected from, say, Ethereum 1. Example, if three transactions have nonce 10, 11, and 12, it was the expectation that transaction 10 would complete before 11 and 12. It has been reported that the transaction with nonce 12 can go through execution before 10.

For folks coming from ETH 1 this could cause some confusion and perhaps be a blocking problem in how a dApp is architected. This issue proposes to elucidate how nonce ordering is expected to behave and be executed once sent.

**Describe the solution you'd like**
The deliverable would be a page (or paragraph) dedicated to explaining how nonces work. Two or three examples with expected results may help drive the point home.

**Comment by mikedotexe** [comment]
@evgenykuzyakov a little bird told me you may have knowledge on this. :)

**Comment by amgando** [comment]
@mikedotexe these are the two authoritative resources that i'm aware of on the subject with relevant highlights extracted.  from these i take away that **nonces are ordered for a given signer account** which means cross-contract transaction execution order is non deterministic.

(1) [runtime](https://docs.google.com/document/d/1VRef627Y-Md1qAdRn0RFUojPxOs5nQmHyHBFYewwbZQ/edit#heading=h.jcaffzoxbeiq)

> - _Nonce - a unique identifier to disambiguate similar transactions_

(2) [nomicon: transaction ordering](https://nomicon.io/ChainSpec/Transactions.html?highlight=nonce#transaction-ordering-example-using-pool-iterator)

> - _Transactions with the same key should be ordered in strictly increasing order of their corresponding nonces_
> - _Pool Iterator iterates over transaction groups until all are empty. It pulls transactions from the group in order from the smallest nonce to largest._
> - _... transactions are valid if the nonce is strictly greater than the previous nonce for the same key._


```
// Verifying nonce
let nonce = tx.nonce();
if let Some(last_nonce) = nonces.get(key) {
    if nonce <= last_nonce {
        // Nonces should increase.
        return false;
    }
}
nonces.insert(key, nonce);
```

**Comment by bowenwang1996** [comment]
> This issue proposes to elucidate how nonce ordering is expected to behave and be executed once sent.

As sherif points out, you can read the detailed explanation if you wish. But the short answer is that validators are free to determine the transactions order, provided that for each access key the nonces are sorted in strictly increasing order (so overall it is topologically sorted).

**Comment by amgando** [comment]
@mikedotexe can we close this?

**Comment by mikedotexe** [comment]
yes, we can close this. a developer who has been building on NEAR for some time was quite positive that the nonce ordering didn't operate sequentially. It sounds like he was confused or mistaken. Thanks for the clarity, all.
