### ISSUE TITLE
[DOC] Document near-api-js usage for blocks/transactions

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#346]
**Is your feature request related to a problem? Please describe.**
Currently there are no documentation that describe how to fetch blocks/chunks/transactions using JS.

**Describe the solution you'd like**
Detail creation of connection and fetching various blockchain info:
```js
const provider = new nearlib.providers.JsonRpcProvider(NODE_URL);
const latest_block =provider.block(null);
const latest_chunk_0 = provider.chunk(latest_block.chunks[0].hash);
const transactions = latest_chunk_0.transactions;
```

**Comment by amgando** [comment]
we have a few of these here from a while ago.  needs some attention tho. 
https://docs.near.org/docs/roles/developer/examples/near-api-js/examples

**Comment by thisisjoshford** [comment]
https://github.com/near/docs/pull/693 Fixes this

Specifically -> https://docs.near.org/docs/api/naj-cookbook#recent-transaction-details
