### ISSUE TITLE
[DOC] Provide details on Rust collections. when to use, not use

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#353]
**Is your feature request related to a problem? Please describe.**
As a Rust developer, I am unsure whether to use Rust's standard collection [HashMap](https://doc.rust-lang.org/beta/std/collections/struct.HashMap.html) or the NEAR collection [Map](https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/collections/map.rs).

**Describe the solution you'd like**
1. Example of when it would make sense to use a HashMap instead of a Map.
2. Example of when it would make sense to use a Map instead of a HashMap.
3. Example of when it would make sense to use a [NEAR Vector](url) instead of a [standard Vec](https://doc.rust-lang.org/beta/std/vec/struct.Vec.html).
4. Example of when it would make sense to use a Vec instead of a standard NEAR Vector.
5. Example of when it would make sense to use a [NEAR Set](https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/collections/set.rs) instead of a [standard HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html).

Discuss the serialization implications, helper functions in standard collections that will be missing the NEAR collections, basic trie explanation, etc.

**Additional context**
For context, internally we have been asked this by prospective projects, so this is less of an exercise in curiosity and filling a need.
There is some documentation that exists for AssemblyScript here:
https://docs.nearprotocol.com/docs/roles/developer/contracts/assemblyscript#collections
that could be useful to borrow the tone/ideas from.

I suggest DevX takes a first stab at this, opens a PR, gets the auto-generated Render link, and shares it with @nearmax, @vgrichina, and @frol.

**Comment by mikedotexe** [comment]
https://github.com/near/partners-flux/issues/1#issuecomment-637069393

**Comment by nearmax** [comment]
Please include @evgenykuzyakov , @fckt , and @willemneal  into the review of the PR.
