### ISSUE TITLE
[DOC] tutorial re: sender vs. predecessor in cross-contract calls

### ISSUE THREAD

**Issue by amgando** [near/docs#358]
`predecessor` sounds like `sender-1`  (but it’s actually `sender - n` where `n` is cross-contract hops)

so `predecessor` on a single contract call could just be set to `sender`, so they would be the same in `as-pect` tests using `Context`

if this doesn't make sense let's close the issue @chadoh

**Comment by janedegtiareva** [comment]
We will benefit from having a tutorial about this.
