### ISSUE TITLE
[DOC] How to do events

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#362]
**Is your feature request related to a problem? Please describe.**
We have a lot of questions about how to do events on NEAR

**Describe the solution you'd like**
We don’t have events as in Ethereum. Instead you can change state and query that via changes RPC - https://docs.near.org/docs/api/rpc-experimental#example-of-data-changes

So your function will be:
```
#[near_bindgen]
#[derive(Default, BorshDeserialize, BorshSerialize)]
struct YourContract {
   events: near_sdk::collections::Vector<(AccountId, Balance)>,
}
#[near_bindgen]
impl YourContract {
#[payable]
pub fn some_func(&mut self) {
   self.events.push((env::predecessor_account_id(), env::attached_deposit()));
}
}
```

**Additional context**
We also want to improve this API - https://github.com/near/near-sdk-rs/issues/162

**Comment by mikedotexe** [comment]
> @mikedotexe can you test this out / add to a demo? should we add it to your intro to Rust page here: http://localhost:3000/docs/tutorials/intro-to-rust

Yeah, I like that idea. This could be a good case for making the Rust counter a multi-part lesson. I'd personally like to keep the current Rust intro as simple as possible. Perhaps we can say, "next, let's add functionality X" and demonstrate this.

**Comment by mikedotexe** [comment]
I think we need to address this issue in `near-api-js` by adding the ability to do this RPC call in that library.
https://github.com/near/near-api-js/issues/390

**Comment by ilblackdragon** [comment]
@thisisjoshford - would be good to add a page about events as it's a frequent question even if it for now just refers to polling the state changes.

Currently the only thing available on docs is this https://docs.near.org/docs/develop/contracts/as/intro#events which is not very helpful and for some reason in AS?
