### ISSUE TITLE
[BUG] Windows instructions include outdated method of running node

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#363]
**Describe the bug**
At this page:
https://docs.near.org/docs/local-setup/running-testnet-windows
there are instructions to use the scripts in `nearcore` in order to start up a local node. That is not the case and we want to always use `nearup` for starting nodes.

**Expected behavior**
When I land on a page describing how to start a local node, I expect the instructions are up to date.

**Comment by chadoh** [comment]
Should we expand this to replace all mentions of the scripts in `nearcore`?

**Comment by amgando** [comment]
any objections to me just blowing away this entire section and rewriting?

**justification**
- there's lots of redundant info here that's covered elsewhere
- much of this content are from legacy pages that i kept from the old state of docs for fear of blowing something away i didn't understand
- `nearup` has it's own repo and in other areas of our docs (APIs for example) we link out to the authoritative resource with (plans for) light treatment of the external content in our docs, but not trying to replace them.  

re: `nearup`, there's no mention of Windows on that page and, although i spun up a Windows instance locally, i'm not sure how much / if any of this content is needed for `nearup` actually.

**recommendation**
1. turn this into an epic that includes the following
  - refactor `Machine Setup` section into 3 pages:
    - Choose a network (new content)
    - Choose a development stack ([like this](https://docs.near.org/docs/local-setup/local-dev-testnet) and [this](https://docs.near.org/docs/quick-start/create-near-app) merged sensibly together)
    - Development lifecycle ([like this](https://github.com/near-examples/workshop--exploring-assemblyscript-contracts/tree/master/assembly/A.sample-projects/01.greeting))
  - test on 3 major operating systems
  - test on multiple version of node?
  - test with feedback from community members?
2. pair on completing the epic with 1 person running macOS, 1 person running Windows (and 1 person testing alignment on Linux afterwards)

**Comment by chadoh** [comment]
I love that idea, @amgando

**Comment by mikedotexe** [comment]
That sounds great! Here's a screenshot of a shared Slack conversation that may be helpful.

<img width="390" alt="Screenshot 2020-06-02 08 25 21" src="https://user-images.githubusercontent.com/1042667/83538447-aa7dfb00-a4aa-11ea-917c-3dea602e7255.png">

**Comment by mikedotexe** [comment]
at this point I think we need to just remove this page from the sidebar as it's incorrect. it's a (possibly much) heavier lift than I think is worth it to invest in redoing the whole thing. please see more info in the above PR description

**Comment by thisisjoshford** [comment]
PR #457 fixes this
