### ISSUE TITLE
[BUG] Hardware requirement for running a node is off

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#364]
In this page https://docs.near.org/docs/roles/validator/hardware we claim that 50GB of disk space is enough, which is not true. I suggest the following:
* [x] Change it to "at least 100GB" and update the cost correspondingly.
* [x] Remove "Windows" in the table as we don't really support it (and has no plan to do so in the foreseeable future).
* [ ] There is no requirement on whether the disk is SSD or HDD. We should not specify SSD here (could be misleading).

**Comment by chadoh** [comment]
@bowenwang1996 given how easy it is to click the "Edit" link and submit these sorts of improvements as a PR, why not do that rather than create an issue?

**Comment by bowenwang1996** [comment]
@chadoh I didn't have time to look up the costs.
