### ISSUE TITLE
[META] add inline executable code samples

### ISSUE THREAD

**Issue by amgando** [near/docs#379]
@willemneal suggested adding something like this to docs to reduce the time to execute code samples as people read through the docs (from the bottom of this page: https://assemblyscript.org)

![image](https://user-images.githubusercontent.com/24913/83784882-44a39600-a699-11ea-9bad-d3c98db1d869.png)

**Comment by thisisjoshford** [comment]
Cleaning up stale issues and going to move this conversation to an ideas section under discussions :)
