### ISSUE TITLE
 Who wants to help with NEAR Explorer development? We have a bunch of UI/react things in explorer that we would love help with: show validator data,   more info for common contracts, better dashboards and more.

### ISSUE THREAD

**Issue by ashleynear** [near/docs#381]
Who wants to help with NEAR Explorer development? We have a bunch of UI/react things in explorer that we would love help with: show validator data,   more info for common contracts, better dashboards and more.

________

This Question came from Tribe. Please respond and tag @ashleynear to get the answer crossposted back to Tribe!

**Comment by amgando** [comment]
closing, not related to docs
