### ISSUE TITLE
[DOC] Explain "Contract-Based Accounts"

### ISSUE THREAD

**Issue by eriktrautman** [near/docs#394]
**Is your feature request related to a problem? Please describe.**
We use the term "contract-based accounts" constantly in marketing materials now but there's actually nowhere that it's explained (that I can find) in the docs and it's led to some confusion.  

**Describe the solution you'd like**
A section within an existing flow (or a new section) which explains how the contract model works and which is linkable from lots of external places would be ideal.  Something terse and technical but which still nods to the business value of this since people linking may be only semi-technical and just wanting to learn one level deeper.

Ideally this should be linked from many places in the docs so it's really easy to find (like "if you want to learn more about NEAR's Contract-based account model, go here...")

**Additional context**
Contract-based accounts are described as offering lots more flexibility for enabling permissions, automations, etc but what are they actually?  This is Illia's explanation via a Slack thread which can probably be the basis for a few paragraphs and an example block:

```
each account has contract_hash
this hash can be 0x0 - then there is no code
or not 0x0 - and then there is code
when we say “contract” we usually mean an account with some deployed code e.g. contract_hash != 0x0, which doesn’t really behave as an account of an individual but represents some applications storing data
contract-based account is an abstraction to describe specific behavior: an account that has contract that controls access to this account
underlying it’s all treated the same.
the easiest to understand is to think that on every account has some code, this code can be empty (contract_hash == 0x0)  . Because you can still try calling methods on a account that has empty code - it just will fail without finding that method.
```

So I imagine:
+ High level explanation of how every account is linked to a contract, which means that methods can be called on that account.  If there isn't a contract linked, that's fine, you just get a standard method-not-found.
+ A few ways this comes up in code (nod to Illia's description of how this is more of an app-oriented behavior than individuals, though it does apply to lockup contracts atop early holder accounts.)

**Comment by amgando** [comment]
@eriktrautman does this page address some / all of your request?
https://docs.near.org/docs/concepts/account

**Comment by amgando** [comment]
there's also this bit that includes a bullet point list of related information

https://github.com/near-examples/workshop--exploring-near-apis#accounts

**Comment by eriktrautman** [comment]
Thanks! Noting Evgeny's explanation too: https://docs.google.com/document/d/1gGGQrKS5twgiLEtgwP0PEZVG176K1Nea9lRgiDsFznA/edit

I think perhaps adding a section that specifically uses the term "contract-based accounts" and notes what Illia said would be helpful (especially so it's searchable) but within this page is likely a good spot.
