### ISSUE TITLE
 As a developer, why are you interested in the contributor program? 

Specifically, what are you looking for that is addressed by the program and what you are looking for that is currently not addressed by the contributor program?

### ISSUE THREAD

**Issue by ashleynear** [near/docs#395]
As a developer, why are you interested in the contributor program? 

Specifically, what are you looking for that is addressed by the program and what you are looking for that is currently not addressed by the contributor program?

________

This Question came from Tribe. Please respond and tag @ashleynear to get the answer crossposted back to Tribe!

**Comment by amgando** [comment]
@ashleynear seems like this came through again for some reason
