### ISSUE TITLE
[DOC] documentation on how to deploy a smart contract

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#440]
It seems that we currently don't have documentation on how to deploy a contract alone. We have some documentation of deployment in the context of app development, but there are people (validators for example) who need to know how to deploy a contract without necessarily knowing about the app development flow.

**Comment by thisisjoshford** [comment]
I believe we do have documentation on how to deploy a smart contract [here](https://docs.near.org/docs/roles/developer/contracts/cli#deploy-a-contract). Would you like more information to be included with this guide?

**Comment by bowenwang1996** [comment]
That looks good. Can we elaborate a bit more on the fact that you have to first create an account and can only then deploy the contract? Even better, it would be nice if there is an example that includes all the steps.
