### ISSUE TITLE
[DOC] Document rpc for querying state changes

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#443]
To understand the changes to accounts at a given block precisely, it is often necessary to query state changes through rpc. We currently don't have much documentation on how to use those endpoints (`EXPERIMENTAL_changes` and `EXPERIMENTAL_changes_in_block`).

**Comment by bowenwang1996** [comment]
@frol can you help with this?

**Comment by thisisjoshford** [comment]
Currently we have [this doc](https://docs.near.org/docs/api/rpc-experimental) @bowenwang1996. Do you want more use case examples?

**Comment by bowenwang1996** [comment]
I see. I was looking at https://docs.near.org/docs/interaction/rpc and didn't find it. Maybe we should point to the experimental endpoints somewhere on the same page? Also should we change the url to https://docs.near.org/docs/api/rpc to be more consistent?

**Comment by thisisjoshford** [comment]
You got it! I will reference and point to the experimental endpoints on the aforementioned page and also change the url for consistency.
