### ISSUE TITLE
[DOC] Criteria for determining whether a transaction has succeeded

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#454]
We should document how to determine precisely whether a transaction has succeeded. More specifically users should be able to tell by issuing a transaction status query.

**Comment by thisisjoshford** [comment]
Do you want a walkthrough on [this query](https://docs.near.org/docs/api/rpc#transaction-status) @bowenwang1996?

**Comment by bowenwang1996** [comment]
Oh I already fixed this in #456.
