### ISSUE TITLE
[META] Configure redirects for old links (when page is moved to a new location)

### ISSUE THREAD

**Issue by frol** [near/docs#455]
**Is your feature request related to a problem? Please describe.**

It is impossible to fix all the links on the Internet, so we should have proper redirects when we move a page, e.g. https://docs.near.org/docs/interaction/rpc has been moved to https://docs.near.org/docs/api/rpc, but the old link is now saying unhelpful "Not Found" blank page. (#453)

**Describe the solution you'd like**

Configure a redirect for the pages that we move.

**Comment by thisisjoshford** [comment]
Implementing a redirect solution using Render's redirect rules. Aforementioned link has been resolved and new redirect workflow will be implemented to avoid any further 404 issues. @frol :)
