### ISSUE TITLE
[BUG] new view ... get_account shows wrong results

### ISSUE THREAD

**Issue by iamveritas** [near/docs#503]
**Describe the bug**

>> near view zavodil.poolv1.near get_account '{"account_id": "my.near"}' --nodeUrl https://rpc.mainnet.near.org

bad result
View call: zavodil.poolv1.near.get_account({"account_id": "my.near"})
{
  account_id: 'my.near',
  unstaked_balance: '0',
  staked_balance: '0',
  can_withdraw: true
}

>> near call my_lockup.lockup.near refresh_staking_pool_balance '' --accountId my.near --nodeUrl https://rpc.mainnet.near.org 

good result:
Fetching total balance from the staking pool @zavodil.poolv1.near
The current total balance on the staking pool is xyzpt (correct amount staked a couple of days ago)

**Expected behavior**
the first command should show correct amount of staked tokens xyzpt like the second one does

I don't know if this is related or not but the staked amount showing in https://wallet.near.org/ it is also zero.

**Comment by thisisjoshford** [comment]
@iamveritas Possibly your issue is not configuring your `NEAR_ENV` to `mainnet`?  

Try: 
`NEAR_ENV=mainnet near view POOL_NAME.poolv1.near get_account '{"account_id": "YOUR_ACCOUNT.near"}'`

Let me know if that works.

**Comment by iamveritas** [comment]
I am passed that at the moment, not really able to go back to try it anytime soon...

**Comment by thisisjoshford** [comment]
ok, no worries! I'm going to close this issue then.  Please feel free to reach out or submit another issue if this does not work for you.
