### ISSUE TITLE
[BUG] rpc call EXPERIMENTAL_tx_status not found

### ISSUE THREAD

**Issue by xianggy** [near/docs#514]
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":"EXPERIMENTAL_tx_status"},"id":96}
request url: https://rpc.mainnet.near.org

**Comment by bowenwang1996** [comment]
It is likely because you are running a version that does not have this endpoint implemented. You can use https://github.com/near/nearcore/releases/tag/1.16.0-rc.2

**Comment by xianggy** [comment]
I use the endpoint URL https://rpc.mainnet.near.org.
I did not run any node.

**Comment by bowenwang1996** [comment]
> I use the endpoint URL https://rpc.mainnet.near.org.

Yeah it doesn't support `EXPERIMENTAL_tx_status` yet

**Comment by 90hacker** [comment]
> > 我使用端点URL https://rpc.mainnet.near.org。
> 
> 是啊它不支持`EXPERIMENTAL_tx_status`尚未

Why not support  `EXPERIMENTAL_tx_status` method

**Comment by bowenwang1996** [comment]
The current release of mainnet doesn't have the commit that implements the endpoint. It should be addressed when we do the next release.
