### ISSUE TITLE
[DOC] add example of account helper to NEAR CLI page

### ISSUE THREAD

**Issue by amgando** [near/docs#520]
**Is your feature request related to a problem? Please describe.**
The current docs for NEAR CLI seem to be missing an example that uses the TestNet faucet account helper

**Describe the solution you'd like**
Let's add this command to this section of the docs: https://docs.near.org/docs/development/near-cli#near-create-account

---

![image](https://user-images.githubusercontent.com/24913/98358528-e6a81f80-2037-11eb-91b0-bab9c83d346c.png)

**Comment by thisisjoshford** [comment]
Tried creating an account using the `--helperUrl` with a `--masterAccount` that did not have sufficient funds like we discussed this morning @amgando, however, the `--helperUrl` did not act as a faucet account to fund it.  I tried several variations /approaches but did not find a solution. I reached out internally for assitance and will update docs with my findings.
