### ISSUE TITLE
[META] Combine Staking and Tokens sections

### ISSUE THREAD

**Issue by eriktrautman** [near/docs#535]
The tokens section was hacked on to fix burning fires around delegation (and doesn't even show up in the main docs page) but it's covering exactly the same type of information as the Staking section so they should be combined into the same docs area (can keep the actual pages separate, of course) so people stop getting confused where to find things.

I envision a single /tokens section which includes the validation docs in one grouping section and the tokens/delegation/lockup-contract stuff in another but whatever feels semantic should be fine. The important thing is that all the info should be in a single place not spread between two related but separate sections.

**Comment by thisisjoshford** [comment]
>The important thing is that all the info should be in a single place not spread between two related but separate sections.

100% agree @eriktrautman. I am currently working on a docs refactoring / consolidating of content that will resolve this and many other issues. :)
