### ISSUE TITLE
[BUG] Old Simulation tests apparently outdated, need an update

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#547]
<img width="1128" alt="Screen Shot 2020-12-05 at 4 31 06 PM" src="https://user-images.githubusercontent.com/1042667/101268420-6698d680-3717-11eb-8901-75461ccadd50.png">

We need to update the docs Simulation Testing
https://docs.near.org/docs/roles/developer/contracts/test-contracts#simulation-tests

For now I'm pointing this person to:
https://github.com/near/near-sdk-rs/blob/master/examples/fungible-token/tests/general.rs

**Comment by mikedotexe** [comment]
This is the newest README on the simulation tests:
https://github.com/near/near-sdk-rs/tree/master/near-sdk-sim

**Comment by thisisjoshford** [comment]
Tracking for this is located in https://github.com/near/docs/issues/638. Closing this issue as I am cleaning up docs tickets.
