### ISSUE TITLE
[DOC] Add view_code RPC endpoint to docs

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#571]
There is a new endpoint `view_code` merged here:
https://github.com/near/nearcore/pull/3714

At the time of this writing it's live on betanet. I think it's fine to have the docs reflect an example that uses env vars for betanet.

http post https://rpc.betanet.near.org jsonrpc=2.0 id=dontcare method=query params:='{"request_type":"view_code","finality":"final","account_id":"mike.betanet"}'

You will get something like the attached output. Truncate the attachment 
[output.txt](https://github.com/near/docs/files/5798018/output.txt)
for the purpose of the example

**Comment by frol** [comment]
There is a PR for that: https://github.com/near/docs/pull/562

**Comment by mikedotexe** [comment]
Closed because Frol is awesome and already did this.
