### ISSUE TITLE
[DOC] Comparison page

### ISSUE THREAD

**Issue by ilblackdragon** [near/docs#572]
**Is your feature request related to a problem? Please describe.**
Clear way to compare NEAR vs XYZ chain / approach.

**Describe the solution you'd like**
There is actually pretty cool example of this https://cloud.google.com/docs/compare/aws/storage that provides comparison across multiple dimension. xDAI, MATIC also have similar pages.

**Comment by bucanero** [comment]
@ilblackdragon , which blockchains should we cover? ethereum, solana, others?
