### ISSUE TITLE
Dapp getting deploy on mainet , but able to deploy on testnet locally

### ISSUE THREAD

**Issue by aj07** [near/docs#573]
Hi,

I am working on a dapp ( https://github.com/aj07/exp_nr ). 

While deploying locally, I am able to deploy things on testnet with frontend running locally. But when I try to run via github (gh pages) . Its taking mainet ( https://aj07.github.io/exp_nr/  ). I don't know why this is happening. 

My team asked on support channel for this bug/issue. They asked to put on issue. Please, help  it.

Thanks!

**Comment by ilblackdragon** [comment]
Hi @aj07 
This doesn't look like documentation issue, so this is probably wrong place for question like this - StackOverflow is probably better.

What are you actually trying to do? It looks like you have setup your Github pages to work with MainNet (e.g. it uses MainNet Wallet) but you did not configure to the right contract (it uses contract name from testnet).

Usually in proper MainNet serving environment, you would provide environment variable used here - https://github.com/aj07/exp_nr/blob/main/src/config.js#L1. But Github doesn't offer such functionality.

So you should consider modifying this line to something that points at your MainNet contract unless there is env variable for testing. Or use other hosting like Netlify where you can use environment variables.

**Comment by ilblackdragon** [comment]
Actually you can just specify your contract name here https://github.com/aj07/exp_nr/blob/main/src/config.js#L11.

**Comment by aj07** [comment]
Thanks for responding @ilblackdragon !  Actaully, I am trying to run it for testnet as of now, for mainnet it will be done proper deployment. 

I checked other repo which is working on testnet and found similar config.js file.  (https://github.com/p2pvid/sdfn/blob/master/src/config.js#L9) But this guest book was getting deployed on testnet.

Again, thanks for your reply

**Comment by aj07** [comment]
I think now it got fixed at https://bit.ly/39dWNYk   .Able to redirect on testnet.

Thanks

**Comment by p2pvid** [comment]
I think now it got fixed at https://bit.ly/39dWNYk .Able to redirect on testnet.

Thanks
