### ISSUE TITLE
[DOC] Need description/summary for cross-contract video

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#577]
Here:
https://docs.near.org/docs/videos/collections-u128-etc#cross-contract-calls-in-rust
We have a very important video but no summary information. Feels like all videos should have a summary that people can read instead of watching the entirety.
Task is to watch the video, take notes, update the page with a few paragraphs below the video explaining it

**Comment by thisisjoshford** [comment]
Closing this issue as we no longer have this video in docs.
