### ISSUE TITLE
[DOC] All NEAR docs chinese translation(Concepts/developer firstly)

### ISSUE THREAD

**Issue by wjy7551376** [near/docs#616]
**Is your feature request related to a problem? Please describe.**
As a blockchain platform, I think we need to translate our developer docs to all language, especially chinese for china developer and let more people konw how to develop their DAPP on NEAR platform to push our ecosystem forward.

**Describe the solution you'd like**
We will fork the repo and translate all docs to Chiense and submit a pr to make the website have Chiense Docs.

**Additional context**

**Comment by thisisjoshford** [comment]
@wjy7551376 Just checking in to see if there was any progress made here :)

**Comment by thisisjoshford** [comment]
@wjy7551376 going to close this issue and consolidate this task in https://github.com/near/docs/issues/621
