### ISSUE TITLE
[META]Integration with LearnNEAR.club

### ISSUE THREAD

**Issue by almal** [near/docs#619]
**Is your feature request related to a problem? Please describe.**
LearnNEAR.club (built on WordPress) is an experimental project with attempt to create an easy onboarding journey for NEAR users and developers.
First phase of it includes Guides, that use docs.near.org repo as ultimate source of info. 
In order to implement that integration required: 

**Describe the solution you'd like**

1. All of the assets to be moved from /docs/assets to /docs/_images
2. Add index.md files to the following folders:

docs/docs/concepts
docs/docs/develop/basics
docs/docs/develop/contracts
docs/docs/develop/evm
docs/docs/develop/front-end
docs/docs/develop/node
docs/docs/tools
docs/docs/validator
docs/docs/tutorials/contracts
docs/docs/tutorials/front-end

 with this content:
 https://github.com/almal/aakash-web/blob/master/docs/git-it-write/index.md

3. Add this webhook for the payload URL:
 https://ngx.f2d.myftpupload.com/wp-json/giw/v1/publish

 if you would like to automatically publish the changes whenever repository is updated.

**Additional context**

**Comment by thisisjoshford** [comment]
I think you found an alternative solution than adding `index.md` to all of docs, correct @almal ? Closing issue :)
