### ISSUE TITLE
[DOC] NEAR Chinese document translation project/NEAR中文文档翻译项目

### ISSUE THREAD

**Issue by viticis** [near/docs#621]
**Is your feature request related to a problem? Please describe.**

I have set up a **NEAR Chinese document translation project**, 
but the translation cannot be completed by myself. 
Contributions are welcome!
我建立了一个**NEAR中文文档翻译项目**，
但是我自己无法完成翻译。
欢迎贡献！

**Describe the solution you'd like**

If you can speak Chinese and love NEAR, please submit a PR.
如果你会中文并且热爱NEAR，欢迎提交PR。
**Additional context**

[NEAR中文文档](https://docs.near.org.cn/)
[Github](https://github.com/near-china/near-china.github.io)

**Comment by thisisjoshford** [comment]
@wjy7551376 @viticis @think-in-universe Let me know if there is any progress in this area and if you three would like to collaborate on this effort as I believe all three of you expressed interest here.

**Comment by bucanero** [comment]
The translation project is now managed using [Crowdin](https://crowdin.com/project/near-docs)

Please check https://docs.near.org/docs/community/contribute/localization for more information.
