### ISSUE TITLE
[BUG] Redirects to moved-pages don't work

### ISSUE THREAD

**Issue by frol** [near/docs#653]
**Describe the bug** 🐞

https://docs.near.org/docs/api/rpc should (and used to) redirect to https://docs.near.org/docs/develop/front-end/rpc

**Comment by thisisjoshford** [comment]
there is an issue with Render's redirects that I'm actively trying to solve. Will notify you once it's fixed.

**Comment by frol** [comment]
It seems that you have moved the page back to its original URL. It would be great to have the redirect from this page: https://docs.near.org/docs/develop/front-end/rpc

**Comment by thisisjoshford** [comment]
> It seems that you have moved the page back to its original URL. It would be great to have the redirect from this page: https://docs.near.org/docs/develop/front-end/rpc

Hey Frol! Sorry for the delay (was OOO Friday)

Creating the redirect from /docs/develop/front-end/rpc to /docs/api/rpc was actually the initial cause of this bug. 

When I created this new redirect and removed the old redirect (from /docs/api/rpc to /docs/develop/front-end/rpc) the old rule did not stop and caused an infinite redirect loop. 😞 I reached out to Render to help resolve the issue and ultimately it just needed 48hrs to resolve itself. Yesterday I added back the initial redirect (from /docs/develop/front-end/rpc to docs/api/rpc) and everything seems to be working as expected.

Please re-open this issue again if you are still experiencing an issue... also note you may need to clear your browser's cache or view it in incognito mode.

**Comment by frol** [comment]
Cool! I think it was caching the redirect response. It works fine now. Thanks!
