### ISSUE TITLE
[DOC] update simple EVM script for Aurora Engine on TestNet

### ISSUE THREAD

**Issue by frankbraun** [near/docs#657]
PR #649 removed the [simple EVM script](https://github.com/near/docs/blob/master/docs/develop/evm/evm-simple.md) from the documentation. It needs to be updated for the Aurora Engine on TestNet.

The page contain JPEGs which refer to BetaNet.

**Comment by mikedotexe** [comment]
Does this still need to be done?

**Comment by frankbraun** [comment]
@artob took over a refactor of the documentation. @artob, can we close this issue?
