### ISSUE TITLE
[BUG] The default allowance of adding key with near-cli is not 0.25

### ISSUE THREAD

**Issue by think-in-universe** [near/docs#660]
**Describe the bug** 🐞

As reported by a developer, the description of the allowance argument in https://docs.near.org/docs/tools/near-cli#2-add-a-function-access-key  is incorrect or out of date.

`--allowance is the amount of Ⓝ the key is allowed to spend on gas fees only and if omitted, 0.25 is the default.`

The allowance is N/A rather than 0.25, if he adds key via near-cli but didn't specify the allowance, e.g.

command: `near add-key example-acct.testnet GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi --contract-id example-contract.testnet`

The allowance is N/A in web wallet: 

![image](https://user-images.githubusercontent.com/46699230/114879688-01c35a80-9e34-11eb-9db8-c6b23469f76c.png)

By looking at the source code, the **near-cli** (https://github.com/near/near-cli/blob/aa7642d414c8a8ee8737e46e9d96c2f5dd002122/commands/add-key.js#L34 ) and **near-api-js** (https://github.com/near/near-api-js/blob/71920e064febe9087c99bcc6a2c17efbfc36b1a5/src/account.ts#L316) didn't set the allowance by default. 

**Expected behavior**

We can fix either the doc by removing the description about the default allowance, or adding the default 0.25 $NEAR allowance in **near-cli** or **near-api-js** .

**Screenshots**
already attached above

**Location** 🎯
https://docs.near.org/docs/tools/near-cli#2-add-a-function-access-key

**Comment by thisisjoshford** [comment]
Just tested this and you're correct @think-in-universe! It seems wallet creates a default of 0.25 N but `near-cli` & `near-api-js` does not. I'm going to update the docs to correct this and will bring this up in the next tooling meeting to see if we should create a default value for this arg.

**Comment by thisisjoshford** [comment]
> Just tested this and you're correct @think-in-universe! It seems wallet creates a default of 0.25 N but `near-cli` & `near-api-js` does not. I'm going to update the docs to correct this and will bring this up in the next tooling meeting to see if we should create a default value for this arg.

thinking about it more @think-in-universe ... there _would_ be use cases where you would want to create a key without any allowance if the key is intended to be used for view call methods only. I updated the PR to include mention of this but will still bring it up during Dev Platform sync tomorrow.

**Comment by think-in-universe** [comment]
@thisisjoshford thanks for the update, Josh.  

> there _would_ be use cases where you would want to create a key without any allowance if the key is intended to be used for view call methods only

In this case, can we set allowance to 0?
