### ISSUE TITLE
[DOC] Document `tx`-like JSON RPC endpoints

### ISSUE THREAD

**Issue by frol** [near/docs#701]
**Is your feature request related to a problem? Please describe.**

It is unclear what all those fields in the `tx` response are used for, e.g. `receipt_outcomes`, `receipts`, `transaction_outcome`, `SuccessReceiptId` status, `receipt_ids` in `outcomes`, etc.

**Describe the solution you'd like**

Reference nomicon and documentation pages talking about execution outcomes, receipts, local receipts, transaction conversion receipt, fees, etc.

**Additional context**

[Indexer for Explorer](https://github.com/near/near-indexer-for-explorer) has most of that information as well, and it will benefit from the explanations as well.

We may want to address this issue first: #700

**Comment by frol** [comment]
It was done a while ago. Here is the structs documentation in the Indexer docs:  https://near-indexers.io/docs/data-flow-and-structures/structures/toc

**Comment by thisisjoshford** [comment]
> It was done a while ago. Here is the structs documentation in the Indexer docs: https://near-indexers.io/docs/data-flow-and-structures/structures/toc

Awesome! Thanks for the update @frol !
