### ISSUE TITLE
[DOC]  Document default size limit for rpc requests to view state

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#732]
**Is your feature request related to a problem? Please describe.**
Developers are not aware that they cannot do a rpc call to view states of contracts that are very large.

**Describe the solution you'd like**
Document the 50kb default limit that we have on viewing state from rpc and also how to change it if you run your own nodes.

**Comment by frol** [comment]
@bowenwang1996 @janewang Ideally, we need a doc about all the configuration (config.json) options, so we can reference to the specific tweaking option from the JSON RPC doc page.

**Comment by frol** [comment]
Resolved in #811.

See it live: https://docs.near.org/docs/api/rpc/contracts#view-contract-state

![image](https://user-images.githubusercontent.com/304265/130614977-62c1e376-d7cb-49f7-a437-7e7193fbce80.png)
