### ISSUE TITLE
[DOC] Consolidate documentation on running a node

### ISSUE THREAD

**Issue by bowenwang1996** [near/docs#735]
**Is your feature request related to a problem? Please describe.**
Currently there are multiple pages on docs.near.org on how to run a node:
* https://docs.near.org/docs/develop/node/running-a-node
* https://docs.near.org/docs/develop/node/compile-and-run-a-node
* https://docs.near.org/docs/validator/staking
* https://docs.near.org/docs/validator/deploy-on-mainnet

They are scattered across different places and some of them contain outdated information, which makes it difficult for a newcomer to actually find the right documentation on how to run a node.

**Describe the solution you'd like**
Documentation on how to run a node should be consolidated in one place. This should include running a validator node, an archival node, and a rpc node.

**Comment by thisisjoshford** [comment]
@bowenwang1996, I was actually just discussing this with @think-in-universe. In addition, these two pending PR's are relevant to this subject and should be taken into consideration when consolidating these docs:
https://github.com/near/docs/pull/706
https://github.com/near/docs/pull/720

Also, merged PR https://github.com/near/docs/pull/721 created the `compile and run a node` section and redundancy was mentioned. @khorolets wanted to leave it as:
>  I would rather get commands for dependencies from there and leave it as is because that part is using nearup which might be useful for someone. I would call the way I described like native one but I'm not sure is this term "native" is correct.

See conversation here: https://github.com/near/docs/pull/721#issuecomment-848628376

If we do ultimately come to the consensus to leave both we should rename one or both to better differentiate the two.

**Comment by janewang** [comment]
Thanks @thisisjoshford for the heads up on #721, #720, and #706. Please chime on how we could consolidate the docs. I'm putting in an initial draft of TOC based on my limited understanding of nodes. 

Would love your feedback on this cc @bowenwang1996 @thisisjoshford @think-in-universe @frol

Run a Node
========
- Introduction
	- Motivation
	- Types of Node
	- [Hardware Requirements](https://docs.near.org/docs/roles/validator/hardware)
		- Minimal Requirements
		- Recommended Requirements
	- [Key Management](https://docs.near.org/docs/validator/keys)
- Run Validator Node
	- [Instructions](https://docs.near.org/docs/validator/staking)
		- Linux and Mac 
			- [Without containerization](https://docs.near.org/docs/develop/node/compile-and-run-a-node) 
			- [With containerization](https://docs.near.org/docs/develop/node/running-a-node)
		- Windows ([are these testnet commands?](https://docs.near.org/docs/develop/node/running-a-node-windows))
	- [Validator Economics](https://docs.near.org/docs/validator/economics)
- Run RPC Node
	- Instructions
		- Linux and Mac 
			- Without containerization 
			- With containerization
		- Windows (are these testnet commands?)
- Run Archival Node
	- Instructions		
		- Linux and Mac 
			- Without containerization 
			- With containerization
		- Windows (are these testnet commands?)
- [Node Maintenance](https://docs.near.org/docs/validator/maintenance)
- Node Operator Community Updates

----------------

Some open questions:
1. Are you generally aligned with this structure or prefer something different?
2. Are running different node types sufficiently different? If so, we could consolidate some instructions.
3. Are hardware requirements vary based on nodes? For example, could RPC use "light node" depending on the type of info requested? If so, hardware requirements could be specific to node type?
4. Windows commands are testnet only. Would it make sense to add mainnet commands here?
5. There is a Google Analytics tag on production documentation site. Could we take a look at GA to see the page traffic, mostly for where to put the navigation.
6. Anything else that would make sense to add here or be taken away?

Thanks for your input!

**Comment by bowenwang1996** [comment]
Discussed it with @janewang today and we decide that we want to remove documentation on windows and validator economics from this page and potentially extract the common setup into a separate section.

**Comment by thisisjoshford** [comment]
> Discussed it with @janewang today and we decide that we want to remove documentation on windows and validator economics from this page and potentially extract the common setup into a separate section.

Sounds good!  

For the above layout @janewang & @bowenwang1996, maybe we should break this down a little differently. Above we have three different types of nodes: Validator, RPC, & Archival. To my understanding, all three of these are almost identical in setup with subtle yet important differences. All nodes expose RPC endpoints by default however validators should have this turned off for optimal performance. Archival nodes are the same as regular nodes but need to change their `config.json` setting archival set to `true`.

Perhaps we should break this down into ways in which you can create nodes. 
   1) Create a node using `nearup` _(with containerization)_
           - with Docker 
           - without Docker
   2) Create a node using `nearcore` _(without containerization)_

Then from here, we can have sections on how to disable RPC endpoints, configure for archival, and become a validator. Also, we may want to put basic information about what a node is under `Concepts>Basics>Node` and link to the `Running a Node` section. 

# Running a Node
## Basics
 - Intro - (Briefly what a node is and types of nodes with a link to `Concepts>Basics>Node` that goes into greater detail.)
 - Key Management 

## Run a node with `nearup`
- Hardware Requirements
- Setup w/ Docker
- Setup w/o Docker
- Windows Setup

## Run a node with `nearcore`
- Hardware Requirements
- Setup
- Windows Setup

## Node Configuration
- Archival
- RPC
- Validator

## Node Maintenance 
- Upgrading a Node
- Planned Updates
- Emergency Updates
- Validator Channels

Not 100% committed to this layout... just helping formulate ideas :)

@khorolets @frol any opinions / suggestions?

**Comment by mikedotexe** [comment]
I think there are a fair number of people abroad that use Windows. Not sure if these instructions are super outdated, but the latest versions of Windows Pro have Docker support.

**Comment by khorolets** [comment]
What I find the best is to split based on type. Like ask yourself what you gonna search if you want to run a validator node, you won't look for running a node and look for configuration. So in my opinion DRY principle is for the code. I would split the info into separate docs in group Running a node.

Introduction
- about that all the nodes are the same code base, different configs, but we've split into section to not mix up all the options.

Run Validator node
- with nearup
  - ...
  - maintenance
    - upgrade
    - planned
    - emergency

- with nearcore
- with docker
- on windows

Run RPC node
 the same sections


I've found it very frustrating to follow some instructions where a lot of "in case of validator do..., and if you ..., for this case..." I want to follow the steps and get my stuff running asap and as easy as possible :) I can deep dive if I want to understand how it is working. IMO. What do you think @mikedotexe @frol @thisisjoshford @bowenwang1996 @janewang ?

**Comment by bowenwang1996** [comment]
> I think there are a fair number of people abroad that use Windows. Not sure if these instructions are super outdated, but the latest versions of Windows Pro have Docker support.

Yeah that is reasonable. Let's keep the documentation, but I will say that there is no guarantee that nearcore works on windows, so maybe we should put some disclaimer there.

**Comment by bowenwang1996** [comment]
> I've found it very frustrating to follow some instructions where a lot of "in case of validator do..., and if you ..., for this case..." I want to follow the steps and get my stuff running asap and as easy as possible

I like the idea. The downside is that we probably have to copy paste more stuff.

**Comment by khorolets** [comment]
> I like the idea. The downside is that we probably have to copy paste more stuff.

Yeah. As I said it's not a code to follow DRY.
