### ISSUE TITLE
[DOC]  add instructions on using public archival nodes

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#752]
**Is your feature request related to a problem? Please describe.**
We have new archival nodes available and should document them for developer visibility.

**Describe the solution you'd like**
Add instructions on using the following node urls in our API docs and `near-api-js` library:
https://archival-rpc.testnet.near.org
https://archival-rpc.betanet.near.org
https://archival-rpc.mainnet.near.org

**Comment by TrevorJTClarke** [comment]
Just a thought -- exposing dapps to use NF archival RPCs is likely not great if they get hammered with traffic. I'd advise others to run their own for archive.

**Comment by thisisjoshford** [comment]
You're probably right @TrevorJTClarke. We have these already mentioned in the [RPC setup docs](https://docs.near.org/docs/api/rpc#setup) and maybe its best to not encourage their use with `near-api-js`. Closing issue :)
