### ISSUE TITLE
NEAR CLI docs to have "view-state"

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#767]
There's a new NEAR CLI command `view-state` that isn't documented here:
https://docs.near.org/docs/tools/near-cli

Note some context:
https://github.com/near/near-cli/pull/799

An example of this on an account that has state:

    near view-state cron.demo.testnet --finality final
    near view-state cron.demo.testnet --blockId 53199035
    near view-state cron.demo.testnet --blockId "DgQKTPJHTZRvuqaChpmuaPkrDCDzSvPSU52SjaUeUdiA"

**Comment by mikedotexe** [comment]
<img width="1551" alt="Screen Shot 2021-06-30 at 10 50 40 AM" src="https://user-images.githubusercontent.com/1042667/124008564-6604ad80-d991-11eb-8837-d40a0d1ee765.png">

 in case we want to show them a handy example. 
 
 Might consider adding text like this:

>"this is not going to be human-readable, but will represent what state exists for this account's contract. This may help some users understand how state and storage look in the raw format…"

**Comment by thisisjoshford** [comment]
Issue resolved, however https://github.com/near/near-cli/pull/799 hasn't been published to `npm` yet @mikedotexe so command with `block-id` doesn't work yet.
