### ISSUE TITLE
[DOC] Change docs about running a node and downloading the config.json and specifying boot nodes

### ISSUE THREAD

**Issue by chefsale** [near/docs#774]
I have implemented:
1) https://github.com/near/nearcore/commit/ac9694aeb1cd2663dfeec71353be9b163552dfc0
2) https://github.com/near/nearcore/commit/7fe68190a5ff01e8da147dbbd8329875b0895312

which provides you the ability to download the config.json from a trusted near S3 bucket and specify boot nodes during the init command, that means that with the next releases this will be available, making some of our documentation obsolete like:
https://docs.near.org/docs/develop/node/archival/run-archival-node-without-nearup#4-replacing-the-configjson

**Comment by janewang** [comment]
@chefsale For this change, the user has to pass in the bootnodes right?
`./target/debug/neard init --chain-id betanet --download-genesis --boot-nodes ed25519:4k9csx6zMiXy4waUvRMPTkEtAS2RFKLVScocR5HwN53P@34.73.25.182:24567,ed25519:4keFArc3M4SE1debUQWi3F1jiuFZSWThgVuA2Ja2p3Jv@34.94.158.10:24567,ed25519:D2t1KTLJuwKDhbcD9tMXcXaydMNykA99Cedz7SkJkdj2@35.234.138.23:24567,ed25519:CAzhtaUPrxCuwJoFzceebiThD9wBofzqqEMCiupZ4M3E@34.94.177.51:24567`

What if they don't know the boot nodes on each network?

**Comment by chefsale** [comment]
Yes, if they don't know they will not specify them :D
