### ISSUE TITLE
[DOC] Explanation of different nets (betanet vs testnet)

### ISSUE THREAD

**Issue by nikurt** [near/docs#777]
**Is your feature request related to a problem? Please describe.**
I got confused by the validator/running-a-node page and assumed that experimenting with running nodes is safer on `testnet` than on `betanet`.

**Describe the solution you'd like**
Please provide a definition of different commonly used nets: localnet, betanet, testnet, mainnet; or link to such definition.

**Comment by bowenwang1996** [comment]
@janewang please take a look
