### ISSUE TITLE
[DOC] Document NEAR CLI command when you want to send empty object

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#808]
Note this exchange on Telegram.

<img width="489" alt="Screen Shot 2021-08-12 at 1 11 42 PM" src="https://user-images.githubusercontent.com/1042667/129263108-5e359e68-0dae-4ec2-bc3a-1ad4c5e00952.png">

Let's clear that up here:
https://docs.near.org/docs/tools/near-cli

**Comment by BenKurrek** [comment]
Created a PR fixing this: 

https://github.com/near/docs/pull/833
