### ISSUE TITLE
[DOC] Document view methods vs change methods explicitly

### ISSUE THREAD

**Issue by frol** [near/docs#818]
**Is your feature request related to a problem? Please describe.**

Currently, there is only a single place where you can learn about view methods and change methods: https://docs.near.org/docs/develop/contracts/as/intro#view-and-change-functions

It does not talk much about the implications and the limitations of those, and it is only found in AssemblyScript development context.

**Describe the solution you'd like**

Change methods are limited by the gas one is willing to pay (specified in the function call action in a transaction). View methods are free of charge since they don't mutate state and don't need to be executed on the validation nodes. View methods are executed on the RPC node and they have to be limited in terms of resources, and the default limit is 200 TGas. RPC nodes are free to change the default, but NEAR public nodes use this default limit.

@thisisjoshford Do you have the capacity / enough context to improve the doc on this topic?

**Comment by frol** [comment]
Related to #671

**Comment by doriancrutcher** [comment]
I can knock this one out

**Comment by gagdiez** [comment]
I added a new section explaining this: https://docs.near.org/develop/contracts/anatomy#public-methods
