### ISSUE TITLE
Zero-to-Hero Crossword

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#820]
The zero-to-hero crossword example is a deliverable for the Dev Platform team for Q3 of 2021. Dev Rel is helping as well. The idea can be understood from resources here:

Resources:
- Video: https://drive.google.com/file/d/1Zs9sHyyY6f2H8IBWEjkq--5MHMeQ5vuy/view
- Slides: https://docs.google.com/presentation/d/19JISbufR1xUlMqgyiUejeIOrCu-DXhd9qRshRhEmhGc/edit#slide=id.gd8531dd72b_0_7
- Modified slides for higher-level view (bootcamp): https://docs.google.com/presentation/d/1DekaQJnjRaS47mo5BBLvJEWBOokJ20oU_ip8PPRKH6I/edit

## Phases

Overall, perhaps start with three phases. (akin to beginner, intermediate, advanced) At the end of each phase there's a final "product" they can take with them.

At the end of phase 1, the user walks away with a crossword puzzle and frontend that allows a user to log in and solve the crossword. The player must have an existing account to be able to log in, and would add the solution public key to themself and then call `submit_solution`. The smart contract checks against the public key but also knows who the predecessor is and that's the account that gets paid the 10 NEAR. This demonstrates the typical way we use function-call access keys.

At the end of phase 2, the product is a crossword puzzle akin to what we have here: https://github.com/near-examples/near-crossword/pull/4. The user playing the crossword puzzle doesn't need to log in. They can create a testnet/mainnet account once they've won. (This differs slightly from the above link as we don't have account creation yet.) This will also involve importing a seed phrase into Wallet. (That PR already stores this info in local storage.) The users walk away understanding callbacks and checking for success/failure.

At the end of phase 3, the user has made optimizations like adding a function that takes Borsh serialized arguments instead of JSON. They also restrict who can call `new_puzzle` to a designated DAO. Demonstrate the ability of having a DAO controlling this smart contract, how removing all access keys would allow this to be fully controlled by voting only. We could also demonstrate the idea of a "staging area upgrade" that's more advanced.

## Thoughts on progressively teaching folks concepts while building

1. The first contract they write in Rust is super simple. Doesn't pay anything out, doesn't touch access keys, just demonstrates how to pass an argument to a Rust smart contract.

  ```rust
  pub fn submit_solution(&mut self, full_answer: String) {
    if full_answer == "sharding subaccount accesskey indexer nonfungible rpc simulation init defi dao" {
      env::log(b"Correct!");
    } else {
      env::log(b"Try again :)");
    }
  }
  ```

  show them logging and how you can see the logs in Explorer, and what Explorer is.

2. Don't have it check the full answer inside `submit_solution` but instead store that in a struct's field, and set that on initialization. This demonstrates using state and the deploy-and-init idea.

3. Don't store the entire seed phrase in state. We could hash the whole seed phrase to make it smaller. Point out that hashing is a one-way process and you **can** derive a hash from the input, but **cannot** derive the input once you have the hash. This is essentially a big part of blockchain, provide links for more info.

  We could use all sorts of hashing functions, but for instructional purposes, let's create a key pair from the crossword solution, treating it as a seed phrase. We'll show why later.

  To create a hash we'll use the public key when we generate a key pair using NEAR CLI. Ask them to install it and run the `near generate-key` command with the seed phrase.

  They'll see that we now have a shorter thing to store on-chain.

  Before it was **78** characters (sharding subaccount accesskey indexer nonfungible rpc simulation init defi dao)
Now it is **52** characters (ed25519:J5VxZNQGvgruC1LRqXCnxzBNhwaHmmEoEXFoxdV9cuXB)

  What are the ways in which this is helpful? Well, let's talk about storage staking on NEAR, linking to docs about how you pay for data you store on the blockchain. Let's use the `near state` command to show how much storage was used in both cases, the "hashed" and non-hashed cases. While we're here, let's talk about the "code hash" that is spit out in the result of that command, and how you can tell if a smart contract is deployed to an account.

4. Next let's introduce the idea of "creating transactions inside a smart contract" because we want to send the winner 10 testnet NEAR if they are correct. But let's go with a little different approach and create a subaccount so we can deploy to that and then call from the parent account and see the transfer of 10 NEAR happened. What are subaccounts… Introduce pattern of deleting and recreating a subaccount when iterating on writing Rust smart contracts.

  By the end of it, they call `submit_solution` on `crossword.friend.testnet` (giving the public key as the parameter) from `friend.testnet`. If it's correct, it transfers 10 testnet NEAR to the predecessor, which is `friend.near`. Go over what predecessor is versus signer versus current account id.

5. Show people Rust Status Message and how you can "log in" using NEAR Wallet. Go over the access keys, how they're visible in the Wallet UI but also using NEAR CLI's near keys friend.testnet 

  **Be very explicit** on which account creates the access key and walk through the process in slow-motion. This is a commonly misunderstood concept, both to new devs and inside NEAR. Show the keys in local storage, use `near keys` before and after on both the smart contract account and the user account.

Continue on with this pace…

**Comment by thisisjoshford** [comment]
Closing as this has been completed and migrated to https://docs.near.org/tutorials/crosswords/basics/overview.
