### ISSUE TITLE
[BUG] Incorrect description of how transaction is rolled back

### ISSUE THREAD

**Issue by nearmax** [near/docs#825]
The following statement is incorrect:

> Receipts may generate other, new receipts which in turn are propagated around the network until all receipts have been applied. If any action within a transaction fails, the entire transaction is rolled back and any unburnt fees are refunded to the proper accounts.

in https://docs.near.org/docs/roles/integrator/faq#how-do-transactions-work-on-the-near-platform

This is not entirely correct. The text implies that the entire transaction is rolled back if any of the action in any of the receipts fails, which is not the case. In fact, speaking very technically, the transaction itself cannot be rolled back, but one or several receipts produced by it can.

CC @bowenwang1996

**Comment by bucanero** [comment]
Just for reference, the `Integrator FAQ` content has been moved to the Wiki: https://wiki.near.org/resources/faq/integrator-faq

Note: I'll update docs.near.org navigation so "Integrator FAQ" redirects to the Wiki

**Comment by bucanero** [comment]
Added a redirect to the Wiki in e549a0f4f507a0ad2d16be2ea4f6afec2aa370c0

**Comment by gagdiez** [comment]
this is better explained now in the cross contract section
