### ISSUE TITLE
Batch transactions vs Batch transaction

### ISSUE THREAD

**Issue by thisisjoshford** [near/docs#826]
Currently, there are two ways to send multiple transactions which we are calling "batch transactions" and "batch transaction".

Batch transaction - sends multiple transactions as one transaction with many actions (gas limit of one call)
Batch transaction**S** - sends multiple transactions as one request to wallet (each with its own gas attached)

We should come up with better names for these to differentiate them. We have batch transaction in the cookbook but should add the second example as well.

**Comment by doriancrutcher** [comment]
It sounds like the tooling and implementation for this is not available in the conventional libraries yet but there something similar available on workspaces-js 

https://github.com/near/workspaces-js/blob/main/packages/js/src/transaction.ts
