### ISSUE TITLE
[BUG] Incorrect complexity for TreeMap access operation

### ISSUE THREAD

**Issue by EquilateralDelta** [near/docs#849]
**Describe the bug** 🐞
Documentation shows complexity for element access in TreeMap as O(log n) while the actual complexity is O(1) as it's just a LookupMap access under the hood. Maybe the 'access' complexity means 'n-th lowest element' instead of 'element by a key x' in which case the complexity is actually O(log n) but I think the latter definition of 'access' is more intuitive.

**Expected behavior**
Complexity displayed is changed to O(1)

**Screenshots**
![image](https://user-images.githubusercontent.com/5846477/133807652-8f59bfd7-85e0-46f1-bc25-d9502159649f.png)

**Location** 🎯
https://docs.near.org/docs/concepts/data-storage#rust-collection-types

**Comment by doriancrutcher** [comment]
I see what you are saying here and I was looking into it but I believe that the if the output is meant to be a tree map, the worst case time complexity would be logarithmic  even if the underlying structures include lookup maps.
