### ISSUE TITLE
[DOC] support the new staking action

### ISSUE THREAD

**Issue by posvyatokum** [near/docs#875]
Part of https://airtable.com/apprrAlfLE1QI6gao/tbl9h3jXf56F4lAql/viw1VzQz6DtES5vbR/rec7i5zgeHPtd6lv7?blocks=hide

**Comment by janewang** [comment]
Based on updated Q4 OKRs, this issue is removed from NodeX Q4 board 
cc @posvyatokum  @bowenwang1996

**Comment by bucanero** [comment]
Hi @janewang , since Node documentation has been moved to `near-nodes.io`, is this issue still valid or relevant to `docs.near.org` ?
