### ISSUE TITLE
Cover the 30% gas rewards

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#884]
There's a very useful feature of NEAR detailed quite briefly here:
https://nomicon.io/Economics/README.html#contract-rewards

Would be great to expand on this in the docs so it's searchable.

There's also a section in [this blog](https://near.org/blog/near-protocol-economics/) under "Contract rewards" that may help.

**Comment by gagdiez** [comment]
Docs now explain that a part of the gas goes to the developer
