### ISSUE TITLE
[DOC] Update Sandbox docs

### ISSUE THREAD

**Issue by mikedotexe** [near/docs#904]
A lot has changed since the sandbox docs were written. I'm not sure how someone is supposed to discover Sandbox testing and the many repos about sandbox, runner, runner-js, workspaces, ava, etc.

Let's figure that out and update the instructions or link to where the best place to start is. My best guess is:
https://github.com/near/workspaces-js

**Comment by bucanero** [comment]
Related to this topic, there was a PR (#805) that was not merged. Perhaps we can resume that work?

**Comment by gagdiez** [comment]
Sandbox is not relevant anymore, now the main integration test suit is workspace, and it is properly documented
